// @vitest-environment node
import { describe, expect, it } from 'vitest';
import type { InfrastructureCapacitySettings, InfrastructureSnapshot } from '../src/models/infrastructure';
import { infrastructureSettingsSchema } from '../server/validators/schemas';
import { InMemoryAuditLogRepository } from '../server/repositories/auditLogRepository';
import { DEFAULT_INFRASTRUCTURE_CAPACITY_SETTINGS, shouldDeleteTechnicalDailySnapshot, type ArtifactRegistryObservation, type InfrastructureRepository, type ReconciliationObservation } from '../server/repositories/infrastructureRepository';
import { InMemoryNotificationOutboxRepository } from '../server/repositories/notificationOutboxRepository';
import { capacityLevel, capacityProjection, InfrastructureService } from '../server/services/infrastructureService';
import type { NotificationService } from '../server/services/notificationService';
import type { PhotoObjectMetadata, PhotoObjectPage, PhotoRepository } from '../server/repositories/photoRepository';
import { InMemoryPhotoMetadataRepository, InMemoryPhotoObjectRepository, InMemoryStorageCleanupTaskRepository } from './helpers/fakePhotoInfrastructure';

function snapshot(id:string,date:string,r2Bytes:number|null,firestoreBytes:number|null=null,artifactBytes:number|null=null):InfrastructureSnapshot{return{id,schemaVersion:1,capturedAt:date,captureSource:'ADMIN',period:date.slice(0,10),r2:{measured:r2Bytes!==null,inventoryComplete:true,objectCount:r2Bytes===null?null:1,bytes:r2Bytes,mainPhotoCount:r2Bytes===null?null:1,thumbnailCount:r2Bytes===null?null:0,oldestObjectAt:null,lastInventoryAt:date},firestore:{counts:{occurrences:1},totalDocuments:1,estimatedLogicalBytes:firestoreBytes,estimationMethod:firestoreBytes===null?'Não medido':'Amostra',documentsSampled:firestoreBytes===null?0:1,coveragePercent:firestoreBytes===null?null:100},notifications:{sentToday:0,sentThisMonth:0,acceptedToday:0,acceptedThisMonth:0,acceptedTotal:0,attemptsStarted:0,attemptsAccepted:0,attemptsDelivered:0,attemptsFailed:0,attemptsBounced:0,attemptsComplained:0,attemptsUncertain:0,retries:0,pending:0,retryPending:0,deliveryUncertain:0,failed:0,failedConfiguration:0,delivered:0,bounced:0,complained:0,unmatchedWebhookPending:0,oldestPendingAt:null,oldestUnmatchedWebhookAt:null,lastAttemptAt:null,lastSuccessfulSendAt:null,lastError:null,lastFailureCategory:null},cleanup:{pendingTasks:0,completedTasks:0,pendingObjects:0,oldestPendingAt:null,lastError:null},artifactRegistry:{collected:artifactBytes!==null,capturedAt:artifactBytes===null?null:date,bytes:artifactBytes,versionCount:artifactBytes===null?null:2,repository:artifactBytes===null?null:'repo'},reconciliation:{missingObjects:0,orphanObjects:0,sizeMismatches:0,lastRunAt:null}};}

class TestInfrastructureRepository implements InfrastructureRepository{
  public settings=structuredClone(DEFAULT_INFRASTRUCTURE_CAPACITY_SETTINGS);public snapshots:InfrastructureSnapshot[]=[];public artifact:ArtifactRegistryObservation|undefined;public reconciliation:ReconciliationObservation|undefined;public cleanupCalls=0;
  public getSettings():Promise<InfrastructureCapacitySettings>{return Promise.resolve(structuredClone(this.settings));}
  public updateSettings(input:Omit<InfrastructureCapacitySettings,'schemaVersion'|'version'|'updatedAt'|'updatedBy'>,expected:number,actor:string):Promise<InfrastructureCapacitySettings>{if(expected!==this.settings.version)return Promise.reject(new Error('INFRASTRUCTURE_SETTINGS_CONFLICT'));this.settings={schemaVersion:1,...input,version:expected+1,updatedAt:new Date().toISOString(),updatedBy:actor};return this.getSettings();}
  public saveSnapshot(value:InfrastructureSnapshot):Promise<void>{this.snapshots=[structuredClone(value),...this.snapshots.filter(item=>item.id!==value.id)];return Promise.resolve();}
  public history(limit=365):Promise<InfrastructureSnapshot[]>{return Promise.resolve(this.snapshots.slice(0,limit));}
  public latest():Promise<InfrastructureSnapshot|null>{return Promise.resolve(this.snapshots[0]??null);}
  public latestArtifactObservation():Promise<ArtifactRegistryObservation|undefined>{return Promise.resolve(this.artifact);}
  public saveReconciliationObservation(value:ReconciliationObservation):Promise<void>{this.reconciliation=structuredClone(value);return Promise.resolve();}
  public latestReconciliationObservation():Promise<ReconciliationObservation|undefined>{return Promise.resolve(this.reconciliation);}
  public collectionCounts():Promise<Record<string,number>>{return Promise.resolve({occurrences:2,events:3,auditLogs:4,notificationOutbox:0});}
  public estimateFirestoreLogicalBytes(limit:number){return Promise.resolve({estimatedLogicalBytes:900,estimationMethod:`Amostra controlada de ${limit} documentos.`,documentsSampled:9,coveragePercent:100});}
  public cleanupTechnicalSnapshots():Promise<number>{this.cleanupCalls+=1;return Promise.resolve(0);}
}

class SyntheticInventoryRepository implements PhotoRepository {
  public readonly provider='r2' as const;
  public constructor(private readonly total:number){}
  public save(_path:string,_buffer:Buffer,_metadata:PhotoObjectMetadata):Promise<void>{void _path;void _buffer;void _metadata;return Promise.resolve();}
  public read(_path:string):Promise<Buffer|undefined>{void _path;return Promise.resolve(undefined);}
  public delete(_path:string):Promise<void>{void _path;return Promise.resolve();}
  public getMetadata(_path:string):Promise<undefined>{void _path;return Promise.resolve(undefined);}
  public listPage(_prefix:string,cursor?:string,limit=500):Promise<PhotoObjectPage>{void _prefix;const start=cursor===undefined?0:Number(cursor);const end=Math.min(this.total,start+limit);const items=Array.from({length:Math.max(0,end-start)},(_,offset)=>({path:`occurrences/o/initial/p-${start+offset}.webp`,size:1}));return Promise.resolve({items,...(end<this.total?{nextCursor:String(end)}:{})});}
}

function notificationStub():NotificationService{return{runtimeStatus:()=>Promise.resolve({provider:'Resend',environmentEnabled:false,applicationEnabled:false,effectiveEnabled:false,from:null,recipientCount:0,configurationIssues:[],metrics:{sentToday:0,sentThisMonth:0,acceptedToday:0,acceptedThisMonth:0,acceptedTotal:0,attemptsStarted:0,attemptsAccepted:0,attemptsDelivered:0,attemptsFailed:0,attemptsBounced:0,attemptsComplained:0,attemptsUncertain:0,retries:0,pending:0,retryPending:0,deliveryUncertain:0,failed:0,failedConfiguration:0,delivered:0,bounced:0,complained:0,unmatchedWebhookPending:0,oldestPendingAt:null,oldestUnmatchedWebhookAt:null,lastAttemptAt:null,lastSuccessfulSendAt:null,lastError:null,lastFailureCategory:null}})} as unknown as NotificationService;}
function makeService(repository=new TestInfrastructureRepository()):{repository:TestInfrastructureRepository;service:InfrastructureService;objects:InMemoryPhotoObjectRepository}{const objects=new InMemoryPhotoObjectRepository();return{repository,objects,service:new InfrastructureService(repository,objects,new InMemoryPhotoMetadataRepository(),new InMemoryStorageCleanupTaskRepository(),new InMemoryNotificationOutboxRepository(),notificationStub(),new InMemoryAuditLogRepository())};}

describe('Infraestrutura e capacidade 0.7.0',()=>{
  it('classifica thresholds configuráveis sem bloquear o serviço',()=>{const settings=DEFAULT_INFRASTRUCTURE_CAPACITY_SETTINGS;expect(capacityLevel(null,settings)).toBe('Não medido');expect(capacityLevel(69.9,settings)).toBe('Normal');expect(capacityLevel(70,settings)).toBe('Atenção');expect(capacityLevel(85,settings)).toBe('Alerta');expect(capacityLevel(95,settings)).toBe('Crítico');});
  it('valida limites e ordem dos thresholds',()=>{const valid={expectedVersion:1,r2StorageReferenceBytes:1,firestoreStorageReferenceBytes:1,artifactRegistryStorageReferenceBytes:1,resendDailyReference:100,resendMonthlyReference:3000,warningPercent:70,alertPercent:85,criticalPercent:95,referenceVerifiedAt:'2026-08-18'};expect(infrastructureSettingsSchema.safeParse(valid).success).toBe(true);expect(infrastructureSettingsSchema.safeParse({...valid,warningPercent:90,alertPercent:80}).success).toBe(false);});
  it('não inventa projeção sem dados ou com crescimento zero',()=>{expect(capacityProjection('R2',null,100,[],item=>item.r2.bytes).message).toContain('Ainda não há histórico');const history=[snapshot('new','2026-08-18T00:00:00.000Z',10),snapshot('old','2026-07-18T00:00:00.000Z',10)];const value=capacityProjection('R2',10,100,history,item=>item.r2.bytes);expect(value.monthsToReference).toBeNull();expect(value.message).toContain('não apresenta crescimento positivo');});
  it('calcula projeção somente com histórico suficiente',()=>{const history=[snapshot('new','2026-08-18T00:00:00.000Z',40),snapshot('old','2026-07-19T00:00:00.000Z',10)];const value=capacityProjection('R2',40,100,history,item=>item.r2.bytes);expect(value.monthlyGrowthBytes).toBe(30);expect(value.monthsToReference).toBe(2);});
  it('captura snapshot agregado, histórico e ausência de Artifact Registry sem dados pessoais',async()=>{const{repository,service,objects}=makeService();await objects.save('occurrences/occ/initial/photo.webp',Buffer.from('1234'),{occurrenceId:'occ',photoId:'photo',kind:'INITIAL'});const captured=await service.captureSnapshot('ADMIN');expect(captured.r2).toMatchObject({measured:true,objectCount:1,bytes:4,mainPhotoCount:1});expect(captured.firestore.totalDocuments).toBe(9);expect(captured.artifactRegistry).toMatchObject({collected:false,bytes:null});expect(repository.cleanupCalls).toBe(1);const serialized=JSON.stringify(captured);for(const forbidden of ['@example.org','trackingKey','description','secret','token'])expect(serialized).not.toContain(forbidden);expect((await service.overview()).history).toHaveLength(1);});
  it('estima Firestore somente por ação administrativa explícita e registra amostra/cobertura',async()=>{const{service}=makeService();const captured=await service.requestFirestoreEstimate(5_000,{id:'admin',uid:'admin',email:'admin@ifes.edu.br',displayName:'Admin',role:'Administrador',teamIds:[],active:true},'correlation');expect(captured.firestore).toMatchObject({estimatedLogicalBytes:900,documentsSampled:9,coveragePercent:100});expect(captured.firestore.estimationMethod).toContain('5000');});
  it('preserva snapshot antigo do Artifact Registry com data observada, sem convertê-lo em zero atual',async()=>{const repository=new TestInfrastructureRepository();repository.artifact={capturedAt:'2025-01-01T00:00:00.000Z',bytes:123,versionCount:7,repository:'repo'};const{service}=makeService(repository);const captured=await service.captureSnapshot('MAINTENANCE_WORKER');expect(captured.artifactRegistry).toMatchObject({collected:true,capturedAt:'2025-01-01T00:00:00.000Z',bytes:123,versionCount:7});});

  it('inventário R2 parcial abaixo da referência não é classificado como Normal nem recebe percentual/projeção integral',async()=>{const repository=new TestInfrastructureRepository();repository.settings={...repository.settings,r2StorageReferenceBytes:100};const partial=snapshot('partial','2026-08-18T00:00:00.000Z',50);partial.r2.inventoryComplete=false;repository.snapshots=[partial];const{service}=makeService(repository);const overview=await service.overview();expect(overview.levels.r2).toEqual({percent:null,level:'Inventário incompleto'});expect(overview.projections.find(item=>item.metric==='R2')).toMatchObject({monthlyGrowthBytes:null,monthsToReference:null});expect(overview.projections.find(item=>item.metric==='R2')?.message).toContain('inventário R2 mais recente é parcial');});
  it('inventário R2 parcial acima da referência já pode sinalizar Crítico sem apresentar percentual integral',async()=>{const repository=new TestInfrastructureRepository();repository.settings={...repository.settings,r2StorageReferenceBytes:100};const partial=snapshot('partial-critical','2026-08-18T00:00:00.000Z',120);partial.r2.inventoryComplete=false;repository.snapshots=[partial];const{service}=makeService(repository);const overview=await service.overview();expect(overview.levels.r2).toEqual({percent:null,level:'Crítico'});});
  it('inventário abaixo do limite de 50.000 objetos termina como integral',async()=>{const repository=new TestInfrastructureRepository();const service=new InfrastructureService(repository,new SyntheticInventoryRepository(49_999),new InMemoryPhotoMetadataRepository(),new InMemoryStorageCleanupTaskRepository(),new InMemoryNotificationOutboxRepository(),notificationStub(),new InMemoryAuditLogRepository());const captured=await service.captureSnapshot('ADMIN');expect(captured.r2).toMatchObject({inventoryComplete:true,objectCount:49_999,bytes:49_999});});
  it('inventário acima do limite de 50.000 é explicitamente parcial e limitado, sem request ilimitado',async()=>{const repository=new TestInfrastructureRepository();const service=new InfrastructureService(repository,new SyntheticInventoryRepository(50_001),new InMemoryPhotoMetadataRepository(),new InMemoryStorageCleanupTaskRepository(),new InMemoryNotificationOutboxRepository(),notificationStub(),new InMemoryAuditLogRepository());const captured=await service.captureSnapshot('ADMIN');expect(captured.r2).toMatchObject({inventoryComplete:false,objectCount:50_000,bytes:50_000});const overview=await service.overview();expect(overview.levels.r2.percent).toBeNull();expect(overview.levels.r2.level).toBe('Inventário incompleto');});
  it('limpa somente snapshot técnico diário antigo com agregado mensal existente',()=>{const now=new Date('2026-08-18T00:00:00.000Z');const old=new Date('2025-01-01T00:00:00.000Z');expect(shouldDeleteTechnicalDailySnapshot('daily-2025-01-01',old,now,true)).toBe(true);expect(shouldDeleteTechnicalDailySnapshot('monthly-2025-01',old,now,true)).toBe(false);expect(shouldDeleteTechnicalDailySnapshot('daily-2025-01-01',old,now,false)).toBe(false);expect(shouldDeleteTechnicalDailySnapshot('daily-2026-08-01',new Date('2026-08-01'),now,true)).toBe(false);});
});
