import { describe, expect, it } from 'vitest';
import type { AuthorizedAdminProfile } from '../src/models/admin';
import { DEFAULT_SERVICE_CALENDAR } from '../server/repositories/referenceSeedData';
import type { OccurrenceEventRecord, StoredOccurrence } from '../server/models/occurrenceDomain';
import { toAdminOccurrence, toPublicOccurrence } from '../server/serializers/occurrenceDto';
import { createInput, makeOccurrenceServiceFixture } from './helpers/occurrenceServiceFixture';

const occurrence:StoredOccurrence={id:'occ',schemaVersion:2,protocol:'INF-2026-000001',trackingKeyHash:'h',trackingKeySalt:'s',reportedCategoryId:'cat',reportedCategoryNameSnapshot:'Categoria',categoryId:'cat',categoryNameSnapshot:'Categoria',reportedLocation:{campusName:'Campus',buildingName:'Bloco',floor:'',room:'Sala'},location:{campusName:'Campus',buildingName:'Bloco',floor:'',room:'Sala'},description:'Descrição suficiente da ocorrência.',immediateRisk:false,status:'Em análise',priority:'Normal',priorityRank:4,assignedTeamId:'team-b',assignedTeamNameSnapshot:'Equipe B',createdAt:new Date('2026-08-17T12:00:00Z'),updatedAt:new Date('2026-08-17T12:00:00Z'),version:1,dataClassification:'REAL',reopenedCount:0,hasPhoto:false,searchTokens:[]};
const event=(id:string,audience:OccurrenceEventRecord['audience'],audienceTeamIdSnapshot?:string):OccurrenceEventRecord=>({id,schemaVersion:2,eventType:'INTERNAL_NOTE_ADDED',visibility:'INTERNAL',audience,...(audienceTeamIdSnapshot?{audienceTeamIdSnapshot}:{}),createdAt:new Date('2026-08-17T13:00:00Z'),actorType:'ADMIN',actorRoleSnapshot:'Gestor',actorDisplayNameSnapshot:'Autor',internalDescription:id,correlationId:'c'});
const events=[event('admin','ADMIN_ONLY'),event('all','ADMINS_AND_MANAGERS'),event('team','RESPONSIBLE_TEAM','team-a')];
const actor=(role:'Administrador'|'Gestor',teamIds:string[]):AuthorizedAdminProfile=>({id:`${role}-id`,uid:`${role}-uid`,email:`${role}@ifes.edu.br`,displayName:role,role,teamIds,active:true});
const policy={calendar:DEFAULT_SERVICE_CALENDAR,exceptions:[]};

describe('audiência das observações internas 0.6.0',()=>{
 it('Administrador visualiza todas as audiências',()=>expect(toAdminOccurrence(occurrence,events,[],actor('Administrador',[]),policy).internalNotes.map(x=>x.id)).toEqual(['admin','all','team']));
 it('Gestor fora da equipe registrada no snapshot não visualiza ADMIN_ONLY nem RESPONSIBLE_TEAM',()=>expect(toAdminOccurrence(occurrence,events,[],actor('Gestor',['team-b']),policy).internalNotes.map(x=>x.id)).toEqual(['all']));
 it('Gestor membro da equipe registrada no momento da nota continua vendo-a mesmo após mudança de equipe da ocorrência',()=>expect(toAdminOccurrence(occurrence,events,[],actor('Gestor',['team-a']),policy).internalNotes.map(x=>x.id)).toEqual(['all','team']));
 it('consulta pública nunca contém observação interna',()=>expect(JSON.stringify(toPublicOccurrence(occurrence,events))).not.toContain('admin'));
 it('backend impede Gestor de criar ADMIN_ONLY',async()=>{const f=makeOccurrenceServiceFixture();const created=await f.service.create(createInput,'create');const stored=await f.occurrences.findByProtocol(created.protocol);await expect(f.service.update(stored!.id,{expectedVersion:1,newInternalNote:'Nota restrita aos administradores.',internalNoteAudience:'ADMIN_ONLY'},f.manager,'note')).rejects.toMatchObject({status:403,code:'FORBIDDEN'});});
 it('backend impede Gestor fora da equipe de criar RESPONSIBLE_TEAM',async()=>{const f=makeOccurrenceServiceFixture();const created=await f.service.create(createInput,'create');const stored=await f.occurrences.findByProtocol(created.protocol);const routed=await f.service.update(stored!.id,{expectedVersion:1,assignedTeamId:'team-admin'},f.administrator,'route');await expect(f.service.update(stored!.id,{expectedVersion:routed.version,newInternalNote:'Nota da equipe responsável.',internalNoteAudience:'RESPONSIBLE_TEAM'},f.secondManager,'note')).rejects.toMatchObject({status:403,code:'FORBIDDEN'});});
 it('Gestor membro registra RESPONSIBLE_TEAM com snapshot da equipe',async()=>{const f=makeOccurrenceServiceFixture();const created=await f.service.create(createInput,'create');const stored=await f.occurrences.findByProtocol(created.protocol);const routed=await f.service.update(stored!.id,{expectedVersion:1,assignedTeamId:'team-admin'},f.administrator,'route');await f.service.update(stored!.id,{expectedVersion:routed.version,newInternalNote:'Nota da equipe responsável.',internalNoteAudience:'RESPONSIBLE_TEAM'},f.manager,'note');const persisted=await f.events.listByOccurrenceId(stored!.id);const note=persisted.find((item)=>item.eventType==='INTERNAL_NOTE_ADDED'&&item.actorType==='ADMIN');expect(note?.audience).toBe('RESPONSIBLE_TEAM');expect(note?.audienceTeamIdSnapshot).toBe('team-admin');});
});
