import { describe, expect, it } from 'vitest';
import { OperationalAdminService } from '../server/services/operationalAdminService';
import { InMemoryAdminUserRepository } from '../server/repositories/adminUserRepository';
import { InMemoryAuditLogRepository } from '../server/repositories/auditLogRepository';
import { REFERENCE_CATEGORIES, REFERENCE_LOCATIONS } from '../server/repositories/referenceSeedData';
import { FakeCategoryRepository, FakeLocationRepository, FakeOccurrenceEventRepository, FakeOccurrenceRepository, FakeOperationalTeamRepository, FakeSlaConfigRepository } from './helpers/fakeRepositories';
import { makeTestPhotoService } from './helpers/fakePhotoInfrastructure';
import { profile } from './helpers/occurrenceServiceFixture';
import type { AdminUser } from '../src/models/admin';
import type { NewOccurrenceEvent, NewOccurrenceRecord, StoredOccurrence } from '../server/models/occurrenceDomain';
import type { StoredPhotoMetadata } from '../server/models/photoDomain';

const toUser=(p:ReturnType<typeof profile>):AdminUser=>({id:p.id,uid:p.uid,email:p.email,normalizedEmail:p.email,displayName:p.displayName,role:p.role,teamIds:p.teamIds,active:true,legacyRole:false,createdAt:'2026-08-01T00:00:00Z',createdBy:'test',updatedAt:'2026-08-01T00:00:00Z',updatedBy:'test'});
function stored(id:string,classification:'REAL'|'TEST'):StoredOccurrence{return{id,schemaVersion:2,protocol:`INF-2026-${id==='test'?'000001':'000002'}`,trackingKeyHash:'hash',trackingKeySalt:'salt',reportedCategoryId:'cat-iluminacao',reportedCategoryNameSnapshot:'Iluminação',categoryId:'cat-iluminacao',categoryNameSnapshot:'Iluminação',reportedLocation:{campusName:'IFES — Campus Barra de São Francisco',buildingId:'bloco-01',buildingName:'Bloco 01',floor:'',roomId:'sala-de-aula-1',room:'SALA DE AULA 1'},location:{campusName:'IFES — Campus Barra de São Francisco',buildingId:'bloco-01',buildingName:'Bloco 01',floor:'',roomId:'sala-de-aula-1',room:'SALA DE AULA 1'},description:'Registro destinado ao teste de expurgo administrativo.',immediateRisk:false,status:'Recebida',priority:'Normal',priorityRank:4,createdAt:new Date('2026-08-17T12:00:00Z'),updatedAt:new Date('2026-08-17T12:00:00Z'),version:1,dataClassification:classification,reopenedCount:0,hasPhoto:false,searchTokens:['registro','teste']};}
function fixture(){const admin=profile('Administrador','admin@ifes.edu.br');const manager=profile('Gestor','gestor@ifes.edu.br');const users=new InMemoryAdminUserRepository([toUser(admin),toUser(manager)]);const audit=new InMemoryAuditLogRepository();const events=new FakeOccurrenceEventRepository();const photo=makeTestPhotoService();const occurrences=new FakeOccurrenceRepository(events,photo.metadata);const service=new OperationalAdminService(new FakeCategoryRepository(structuredClone(REFERENCE_CATEGORIES)),new FakeLocationRepository(structuredClone(REFERENCE_LOCATIONS)),new FakeOperationalTeamRepository(),new FakeSlaConfigRepository(),users,occurrences,audit,photo.service);return{service,admin,manager,audit,occurrences,events,photo};}

describe('administração estrutural e exclusão segura 0.6.0',()=>{
 it('Gestor não cria categoria/equipe nem altera SLA',async()=>{const f=fixture();await expect(f.service.createCategory({name:'Nova categoria',description:'Categoria de teste.',active:true,sortOrder:90,resolutionBaseBusinessHours:20},f.manager,'c')).rejects.toMatchObject({status:403});await expect(f.service.createTeam({name:'Equipe',sortOrder:1},f.manager,'c')).rejects.toMatchObject({status:403});const settings=await f.service.getSlaSettings();await expect(f.service.updateSlaConfig(settings.config,settings.config.version,f.manager,'c')).rejects.toMatchObject({status:403});});
 it('Administrador cria categoria e equipe e registra auditoria',async()=>{const f=fixture();const category=await f.service.createCategory({name:'Categoria complementar',description:'Cadastro institucional complementar.',active:true,sortOrder:90,resolutionBaseBusinessHours:20},f.admin,'cat');const team=await f.service.createTeam({name:'Equipe de Manutenção',sortOrder:1,memberAdminUserIds:[f.admin.id]},f.admin,'team');expect(category.version).toBe(1);expect(team.memberAdminUserIds).toContain(f.admin.id);expect((await f.audit.list(20)).map(x=>x.eventType)).toEqual(expect.arrayContaining(['CATEGORY_CREATED','TEAM_CREATED']));});
 it('Administrador expurga TEST com metadados/fotografias, Gestor é bloqueado e REAL nunca é apagada',async()=>{const f=fixture();f.occurrences.setDirect(stored('test','TEST'));f.occurrences.setDirect(stored('real','REAL'));const photo:StoredPhotoMetadata={id:'photo-1',schemaVersion:1,kind:'INITIAL',visibility:'INTERNAL',status:'READY',storagePath:'occurrences/test/initial/photo-1.webp',thumbnailStoragePath:'occurrences/test/initial-thumbnails/photo-1.webp',contentType:'image/webp',width:10,height:10,byteSize:3,thumbnailByteSize:2,sha256:'abc',createdAt:new Date('2026-08-17T12:00:00Z'),createdByType:'PUBLIC'};f.photo.metadata.create('test',[photo]);await f.photo.objects.save(photo.storagePath,Buffer.from('abc'),{occurrenceId:'test',photoId:photo.id,kind:'INITIAL'});await f.photo.objects.save(photo.thumbnailStoragePath,Buffer.from('ab'),{occurrenceId:'test',photoId:photo.id,kind:'INITIAL'});const event:NewOccurrenceEvent={schemaVersion:2,eventType:'OCCURRENCE_CREATED',visibility:'PUBLIC',createdAt:new Date('2026-08-17T12:00:00Z'),actorType:'SYSTEM',publicDescription:'Criada.',correlationId:'c'};f.events.append('test',[event]);await expect(f.service.purgeTestOccurrence('test',f.manager,'c')).rejects.toMatchObject({status:403});await expect(f.service.purgeTestOccurrence('real',f.admin,'c')).rejects.toMatchObject({status:403});await f.service.purgeTestOccurrence('test',f.admin,'c');expect(await f.occurrences.getById('test')).toBeUndefined();expect(await f.events.listByOccurrenceId('test')).toEqual([]);expect(await f.photo.metadata.listByOccurrenceId('test')).toEqual([]);expect(f.photo.objects.paths()).toEqual([]);expect((await f.audit.list(20)).some(x=>x.eventType==='TEST_OCCURRENCE_DELETED')).toBe(true);await expect(f.service.purgeTestOccurrence('test',f.admin,'c')).rejects.toMatchObject({status:404});});
 it('expurgo não reutiliza protocolo e a limpeza de objetos é idempotente',async()=>{const f=fixture();const input:NewOccurrenceRecord={categoryId:'cat-iluminacao',categoryNameSnapshot:'Iluminação',location:stored('x','TEST').location,description:'Registro TEST para contador.',immediateRisk:false,priority:'Normal',trackingKeyHash:'hash',trackingKeySalt:'salt',dataClassification:'TEST',searchTokens:['registro']};const event:NewOccurrenceEvent={schemaVersion:2,eventType:'OCCURRENCE_CREATED',visibility:'PUBLIC',createdAt:new Date('2026-08-17T12:00:00Z'),actorType:'SYSTEM',publicDescription:'Criada.',correlationId:'c'};const first=await f.occurrences.createWithProtocol(input,'INF',[event]);await f.service.purgeTestOccurrence(first.id,f.admin,'c');const second=await f.occurrences.createWithProtocol(input,'INF',[{...event,createdAt:new Date('2026-08-17T13:00:00Z')}]);expect(second.protocol).not.toBe(first.protocol);expect(second.protocol.endsWith('000002')).toBe(true);const metadata:StoredPhotoMetadata={id:'gone',schemaVersion:1,kind:'INITIAL',visibility:'INTERNAL',status:'READY',storagePath:'occurrences/test/initial/gone.webp',thumbnailStoragePath:'occurrences/test/initial-thumbnails/gone.webp',contentType:'image/webp',width:1,height:1,byteSize:1,thumbnailByteSize:1,sha256:'abc',createdAt:new Date(),createdByType:'PUBLIC'};await f.photo.service.deleteObjectsOrQueue(metadata,'teste idempotente','c1');await f.photo.service.deleteObjectsOrQueue(metadata,'teste idempotente','c2');expect(await f.photo.cleanup.listPending()).toEqual([]);});
});
