import { describe, expect, it } from 'vitest';
import type { StoredOccurrence } from '../server/models/occurrenceDomain';
import { FakeOccurrenceEventRepository, FakeOccurrenceRepository } from './helpers/fakeRepositories';
import { profile } from './helpers/occurrenceServiceFixture';

function item(i:number):StoredOccurrence{return{id:`occ-${String(i).padStart(3,'0')}`,schemaVersion:2,protocol:`INF-2026-${String(i).padStart(6,'0')}`,trackingKeyHash:'h',trackingKeySalt:'s',reportedCategoryId:'cat',reportedCategoryNameSnapshot:'Categoria',categoryId:'cat',categoryNameSnapshot:'Categoria',reportedLocation:{campusName:'Campus',buildingId:'bloco-01',buildingName:'Bloco 01',floor:'',room:`Sala ${i}`},location:{campusName:'Campus',buildingId:'bloco-01',buildingName:'Bloco 01',floor:'',roomId:`sala-${i}`,room:`Sala ${i}`},description:`Ocorrência ${i}`,immediateRisk:false,status:'Recebida',priority:i%5===0?'Urgente':'Normal',priorityRank:i%5===0?2:4,createdAt:new Date(Date.UTC(2026,7,1,12,0,i)),updatedAt:new Date(Date.UTC(2026,7,1,12,0,i)),version:1,dataClassification:i%2===0?'TEST':'REAL',reopenedCount:0,hasPhoto:i%3===0,searchTokens:['ocorrencia',String(i)]};}

describe('paginação por cursor e filtros 0.6.0',()=>{
 it('pagina 25 registros sem duplicar nem omitir entre páginas',async()=>{const repo=new FakeOccurrenceRepository(new FakeOccurrenceEventRepository());for(let i=1;i<=60;i++)repo.setDirect(item(i));const user=profile('Gestor');const p1=await repo.list({pageSize:25,sort:'oldest'},user);const p2=await repo.list({pageSize:25,sort:'oldest',cursor:p1.nextCursor},user);const p3=await repo.list({pageSize:25,sort:'oldest',cursor:p2.nextCursor},user);expect(p1.items).toHaveLength(25);expect(p2.items).toHaveLength(25);expect(p3.items).toHaveLength(10);expect(new Set([...p1.items,...p2.items,...p3.items].map(x=>x.id)).size).toBe(60);expect(p3.hasMore).toBe(false);});
 it('aceita páginas 50 e 100 preservando filtros',async()=>{const repo=new FakeOccurrenceRepository(new FakeOccurrenceEventRepository());for(let i=1;i<=80;i++)repo.setDirect(item(i));const user=profile('Gestor');const fifty=await repo.list({pageSize:50,dataClassification:'TEST',sort:'oldest'},user);expect(fifty.items).toHaveLength(40);expect(fifty.items.every(x=>x.dataClassification==='TEST')).toBe(true);const hundred=await repo.list({pageSize:100,withPhoto:true,sort:'newest'},user);expect(hundred.items.every(x=>x.hasPhoto)).toBe(true);expect(hundred.items.length).toBe(26);});
 it('ordenação operacional prioriza prioridade e depois SLA/antiguidade',async()=>{const repo=new FakeOccurrenceRepository(new FakeOccurrenceEventRepository());repo.setDirect(item(1));repo.setDirect(item(5));const result=await repo.list({pageSize:25,sort:'operational'},profile('Gestor'));expect(result.items[0]?.priority).toBe('Urgente');});
});
