// @vitest-environment node
import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

const tempDirectories: string[] = [];

async function createPackageFixture(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), 'odc-production-package-'));
  tempDirectories.push(root);
  await mkdir(join(root, 'scripts'), { recursive: true });
  await mkdir(join(root, 'node_modules', 'prod-only'), { recursive: true });
  await mkdir(join(root, 'node_modules', 'dev-only'), { recursive: true });

  const scriptSource = await readFile(
    new URL('../scripts/prepareProductionPackage.mjs', import.meta.url),
    'utf8',
  );

  await writeFile(join(root, 'scripts', 'prepareProductionPackage.mjs'), scriptSource);
  await writeFile(
    join(root, 'package.json'),
    JSON.stringify({
      name: 'odc-production-package-fixture',
      version: '1.0.0',
      dependencies: { 'prod-only': '1.0.0' },
      devDependencies: { 'dev-only': '1.0.0' },
    }),
  );
  await writeFile(join(root, 'node_modules', 'prod-only', 'package.json'), '{"name":"prod-only","version":"1.0.0"}');
  await writeFile(join(root, 'node_modules', 'dev-only', 'package.json'), '{"name":"dev-only","version":"1.0.0"}');
  await writeFile(join(root, 'bun.lock'), 'generated by environment');
  await writeFile(join(root, 'bun.lockb'), 'generated by environment');

  return root;
}

afterEach(async () => {
  await Promise.all(tempDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true })));
});

describe('production package preparation 0.6.1', () => {
  it('removes dev-only modules and Bun lockfiles while preserving production modules', async () => {
    const root = await createPackageFixture();
    const result = spawnSync(process.execPath, ['scripts/prepareProductionPackage.mjs'], {
      cwd: root,
      encoding: 'utf8',
    });

    expect(result.status, `${result.stdout}\n${result.stderr}`).toBe(0);
    expect(existsSync(join(root, 'node_modules', 'dev-only'))).toBe(false);
    expect(existsSync(join(root, 'node_modules', 'prod-only'))).toBe(true);
    expect(existsSync(join(root, 'bun.lock'))).toBe(false);
    expect(existsSync(join(root, 'bun.lockb'))).toBe(false);
  });

  it('keeps package.json build configured to run the production-package preparation', () => {
    const packageJson = JSON.parse(execFileSync(process.execPath, ['-e', 'process.stdout.write(JSON.stringify(require("./package.json")))'], {
      cwd: process.cwd(),
      encoding: 'utf8',
    })) as { scripts?: Record<string, string> };

    expect(packageJson.scripts?.build).toContain('node scripts/prepareProductionPackage.mjs');
    expect(packageJson.scripts?.['prepare:production-package']).toBe('node scripts/prepareProductionPackage.mjs');
  });
});
