import { MailCheck, Plus, Save, Send, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import type { SystemConfig } from '../../models/config';
import type { NotificationStatus } from '../../models/infrastructure';
import { configService } from '../../services/configService';
import { notificationService } from '../../services/notificationService';
import { getErrorMessage } from '../../utils/errors';
import { StatusAlert } from '../common/StatusAlert';

export function NotificationSettingsPanel():React.JSX.Element{
 const[config,setConfig]=useState<SystemConfig|null>(null);const[status,setStatus]=useState<NotificationStatus|null>(null);const[email,setEmail]=useState('');const[testRecipient,setTestRecipient]=useState('');const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);
 const load=async()=>{const[c,s]=await Promise.all([configService.getOperationalConfig(),notificationService.status()]);setConfig(c);setStatus(s);setTestRecipient(current=>current===''?(c.notificationEmails[0]??''):current);};
 useEffect(()=>{let active=true;void Promise.all([configService.getOperationalConfig(),notificationService.status()]).then(([c,s])=>{if(!active)return;setConfig(c);setStatus(s);setTestRecipient(c.notificationEmails[0]??'');}).catch(caught=>{if(active)setError(getErrorMessage(caught));});return()=>{active=false;};},[]);
 const add=(event:FormEvent)=>{event.preventDefault();if(!config)return;const normalized=email.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/u.test(normalized)){setError('Informe um endereço de e-mail válido.');return;}if(config.notificationEmails.length>=20){setError('O limite de 20 destinatários foi atingido.');return;}if(!config.notificationEmails.includes(normalized))setConfig({...config,notificationEmails:[...config.notificationEmails,normalized]});setEmail('');setError(null);};
 const save=async()=>{if(!config)return;setBusy(true);try{await configService.updateConfig({notificationEmails:config.notificationEmails,emailNotificationsEnabled:config.emailNotificationsEnabled});await load();setMessage('Configuração de notificações salva e auditada.');setError(null);}catch(caught){setError(getErrorMessage(caught));}finally{setBusy(false);}};
 const sendTest=async()=>{if(testRecipient===''){setError('Selecione ou informe um destinatário para o teste.');return;}setBusy(true);try{await notificationService.test(testRecipient);setMessage('E-mail de teste registrado na outbox. A entrega ocorrerá pelo mesmo fluxo transacional.');setError(null);await load();}catch(caught){setError(getErrorMessage(caught));}finally{setBusy(false);}};
 if(config===null)return <section className="border border-slate-300 p-5" aria-busy="true"><h2 className="text-xl font-bold">Notificações institucionais</h2><p>Carregando configuração…</p></section>;
 return <section className="space-y-5 border border-slate-300 p-5" aria-labelledby="notification-settings-title"><div><h2 id="notification-settings-title" className="flex items-center gap-2 text-xl font-bold"><MailCheck className="h-5 w-5" aria-hidden="true"/>Notificações institucionais por e-mail</h2><p className="mt-1 text-sm text-slate-700">Cada destinatário recebe uma entrega independente pela outbox. Endereços não são expostos entre si.</p></div>{error&&<StatusAlert tone="error">{error}</StatusAlert>}{message&&<StatusAlert tone="success">{message}</StatusAlert>}
 <dl className="grid gap-3 sm:grid-cols-3"><div><dt className="detail-term">Provedor</dt><dd className="detail-value">{status?.provider ?? 'Resend'}</dd></div><div><dt className="detail-term">Envio efetivo</dt><dd className="detail-value">{status?.effectiveEnabled?'Habilitado':'Desabilitado'}</dd></div><div><dt className="detail-term">Remetente configurado</dt><dd className="detail-value break-all">{status?.from??'Não configurado'}</dd></div></dl>
 {status!==null&&status.configurationIssues.length>0&&<StatusAlert tone="info"><strong>Verificações de configuração:</strong><ul className="mt-1 list-disc pl-5">{status.configurationIssues.map(issue=><li key={issue}>{issue}</li>)}</ul></StatusAlert>}
 {status!==null&&<dl className="grid gap-3 sm:grid-cols-3"><div><dt className="detail-term">Entregas incertas</dt><dd className="detail-value">{status.metrics.deliveryUncertain}</dd></div><div><dt className="detail-term">Falhas de configuração</dt><dd className="detail-value">{status.metrics.failedConfiguration}</dd></div><div><dt className="detail-term">Última categoria de falha</dt><dd className="detail-value">{status.metrics.lastFailureCategory??'Nenhuma'}</dd></div></dl>}
 <label className="flex min-h-11 items-center gap-2 font-semibold"><input id="enable-notifications" aria-label="Habilitar notificações para novas ocorrências reais" type="checkbox" checked={config.emailNotificationsEnabled} onChange={event=>setConfig({...config,emailNotificationsEnabled:event.target.checked})}/>Habilitar notificações para novas ocorrências reais</label>
 <div><h3 className="font-bold">Destinatários ({config.notificationEmails.length}/20)</h3><form className="mt-2 flex flex-col gap-2 sm:flex-row" onSubmit={add}><label className="sr-only" htmlFor="new-notification-email">Novo destinatário</label><input id="new-notification-email" aria-label="Endereço de e-mail do novo destinatário" className="form-control" type="email" maxLength={254} placeholder="destinatario@dominio.example" value={email} onChange={event=>setEmail(event.target.value)}/><button className="btn-secondary min-h-11" type="submit"><Plus className="h-4 w-4" aria-hidden="true"/>Adicionar</button></form><ul className="mt-3 space-y-2">{config.notificationEmails.length===0?<li className="text-sm text-slate-600">Nenhum destinatário configurado.</li>:config.notificationEmails.map(recipient=><li key={recipient} className="flex items-center justify-between gap-3 border border-slate-200 p-3"><span className="break-all">{recipient}</span><button type="button" className="btn-secondary min-h-11" aria-label={`Remover ${recipient}`} onClick={()=>setConfig({...config,notificationEmails:config.notificationEmails.filter(value=>value!==recipient)})}><Trash2 className="h-4 w-4" aria-hidden="true"/>Remover</button></li>)}</ul></div>
 <button className="btn-primary min-h-11" type="button" disabled={busy} onClick={()=>void save()}><Save className="h-4 w-4" aria-hidden="true"/>Salvar notificações</button>
 <div className="border-t border-slate-300 pt-5"><h3 className="font-bold">Enviar e-mail de teste</h3><p className="mt-1 text-sm text-slate-700">O teste utiliza a outbox, é auditado e processado pelo provedor ativo.</p><div className="mt-2 flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor="test-email-recipient">Destinatário do teste</label><input id="test-email-recipient" aria-label="Destinatário para o envio do e-mail de teste" className="form-control" type="email" list="configured-notification-emails" value={testRecipient} onChange={event=>setTestRecipient(event.target.value)}/><datalist id="configured-notification-emails">{config.notificationEmails.map(recipient=><option value={recipient} key={recipient}/>)}</datalist><button className="btn-secondary min-h-11" type="button" disabled={busy} onClick={()=>void sendTest()}><Send className="h-4 w-4" aria-hidden="true"/>Registrar teste</button></div></div>
 </section>;
}
