import type { AuthorizedAdminProfile } from '../../src/models/admin';
import type { InternalNote, Occurrence, OccurrencePhoto, OccurrenceSla, PublicMessage, PublicOccurrence, PublicOccurrencePhoto, TimelineEvent } from '../../src/models/occurrence';
import type { BusinessTimePolicy } from '../domain/businessTime';
import { calculateSlaFilterStatus, effectiveResolutionMinutes, policyForSla } from '../domain/sla';
import type { OccurrenceEventRecord, StoredOccurrence, StoredOccurrenceSla } from '../models/occurrenceDomain';
import type { StoredPhotoMetadata } from '../models/photoDomain';
function iso(v:Date):string{return v.toISOString();}
function title(e:OccurrenceEventRecord):string{switch(e.eventType){case'OCCURRENCE_CREATED':return'Ocorrência registrada';case'STATUS_CHANGED':return e.newValue?`Situação alterada para ${e.newValue}`:'Situação atualizada';case'CATEGORY_CHANGED':return'Categoria ajustada após triagem';case'LOCATION_CHANGED':return'Localização ajustada após triagem';case'PRIORITY_CHANGED':return'Prioridade atualizada';case'TEAM_ASSIGNED':case'TEAM_CHANGED':return'Equipe responsável atualizada';case'RESPONSIBLE_CHANGED':return'Gestor responsável atualizado';case'PUBLIC_MESSAGE_ADDED':return'Nova mensagem pública registrada';case'INTERNAL_NOTE_ADDED':return'Observação administrativa registrada';case'DUPLICATE_LINKED':return'Ocorrência identificada como duplicada';case'DUPLICATE_UNLINKED':return'Vínculo de duplicidade removido';case'DATA_CLASSIFICATION_CHANGED':return'Classificação do registro atualizada';case'OCCURRENCE_ATTACHED':return'Ocorrência apensada';case'OCCURRENCE_DETACHED':return'Ocorrência desapensada';case'OCCURRENCE_RESOLVED':return'Ocorrência resolvida';case'OCCURRENCE_CLOSED':return'Ocorrência encerrada';case'OCCURRENCE_REOPENED':return'Ocorrência reaberta';case'SLA_PAUSED':return'SLA efetivo pausado';case'SLA_RESUMED':return'SLA efetivo retomado';case'PHOTO_ADDED':case'PHOTO_DELETED':case'PHOTO_VISIBILITY_CHANGED':return'Registro fotográfico atualizado';}}
function canSeeEvent(e:OccurrenceEventRecord,o:StoredOccurrence,u:AuthorizedAdminProfile):boolean{
  if(e.eventType!=='INTERNAL_NOTE_ADDED')return true;
  const a=e.audience??'ADMINS_AND_MANAGERS';
  if(u.role==='Atendente'){
    if(a!=='RESPONSIBLE_TEAM')return false;
    const teamId=e.audienceTeamIdSnapshot??o.assignedTeamId;
    return o.assignedToAdminUserId===u.id&&(teamId===undefined||u.teamIds.includes(teamId));
  }
  if(a==='ADMINS_AND_MANAGERS')return true;
  if(a==='ADMIN_ONLY')return u.role==='Administrador';
  const teamId=e.audienceTeamIdSnapshot??o.assignedTeamId;
  return u.role==='Administrador'||(teamId!==undefined&&u.teamIds.includes(teamId));
}
function adminTimeline(e:OccurrenceEventRecord):TimelineEvent{return{id:e.id,date:iso(e.createdAt),title:title(e),description:e.internalDescription??e.publicDescription,isPublic:e.visibility==='PUBLIC',authorRole:e.actorRoleSnapshot};}
function publicTimeline(e:OccurrenceEventRecord):TimelineEvent{return{id:e.id,date:iso(e.createdAt),title:title(e),...(e.publicDescription?{description:e.publicDescription}:{}),isPublic:true};}
function publicMessage(e:OccurrenceEventRecord,admin:boolean):PublicMessage{return{id:e.id,date:iso(e.createdAt),message:e.publicDescription??'',authorRole:admin?(e.actorRoleSnapshot??'Sistema'):'Equipe responsável'};}
function internalNote(e:OccurrenceEventRecord):InternalNote{return{id:e.id,date:iso(e.createdAt),note:e.internalDescription??'',authorName:e.actorDisplayNameSnapshot??'Sistema',authorRole:e.actorRoleSnapshot??'Sistema',audience:e.audience??'ADMINS_AND_MANAGERS'};}
function adminPhoto(p:StoredPhotoMetadata):OccurrencePhoto{return{id:p.id,kind:p.kind,visibility:p.visibility,status:p.status,width:p.width,height:p.height,byteSize:p.byteSize,createdAt:iso(p.createdAt)};}
function publicPhoto(p:StoredPhotoMetadata):PublicOccurrencePhoto{return{id:p.id,kind:'RESOLUTION',createdAt:iso(p.createdAt),width:p.width,height:p.height};}
function dtoSla(s:StoredOccurrenceSla,createdAt:Date,now:Date,fallbackPolicy:BusinessTimePolicy):OccurrenceSla{const policy=policyForSla(s,fallbackPolicy);const effective=effectiveResolutionMinutes(createdAt,now,s,policy);return{schemaVersion:1,policyVersion:s.policyVersion,firstResponseTargetBusinessMinutes:s.firstResponseTargetBusinessMinutes,firstResponseDueAt:iso(s.firstResponseDueAt),...(s.firstResponseAt?{firstResponseAt:iso(s.firstResponseAt)}:{}),...(s.firstResponseOutcome?{firstResponseOutcome:s.firstResponseOutcome}:{}),resolutionBaseBusinessMinutes:s.resolutionBaseBusinessMinutes,priorityMultiplier:s.priorityMultiplier,resolutionTargetBusinessMinutes:s.resolutionTargetBusinessMinutes,resolutionDueAt:iso(s.resolutionDueAt),resolutionNearDueAt:iso(s.resolutionNearDueAt),resolutionPaused:s.resolutionPaused,...(s.resolutionPauseStartedAt?{resolutionPauseStartedAt:iso(s.resolutionPauseStartedAt)}:{}),accumulatedPausedBusinessMinutes:s.accumulatedPausedBusinessMinutes,effectiveElapsedBusinessMinutes:effective,...(s.completedAt?{completedAt:iso(s.completedAt)}:{}),...(s.resolutionOutcome?{resolutionOutcome:s.resolutionOutcome}:{}),calendarSnapshotId:s.calendarSnapshotId,...(s.legacyAssessment?{legacyAssessment:s.legacyAssessment}:{})};}
export function toAdminOccurrence(o:StoredOccurrence,events:OccurrenceEventRecord[],photos:StoredPhotoMetadata[]=[],user:AuthorizedAdminProfile,policy:BusinessTimePolicy,now=new Date()):Occurrence{const visible=events.filter(e=>canSeeEvent(e,o,user));const sla=o.sla;return{id:o.id,protocol:o.protocol,reportedLocation:structuredClone(o.reportedLocation),location:structuredClone(o.location),reportedCategoryId:o.reportedCategoryId,reportedCategoryName:o.reportedCategoryNameSnapshot,categoryId:o.categoryId,categoryName:o.categoryNameSnapshot,description:o.description,immediateRisk:o.immediateRisk,status:o.status,priority:o.priority,...(o.assignedTeamId?{assignedTeamId:o.assignedTeamId}:{}),...(o.assignedTeamNameSnapshot?{assignedTeamNameSnapshot:o.assignedTeamNameSnapshot}:{}),...(o.assignedToAdminUserId?{assignedToAdminUserId:o.assignedToAdminUserId}:{}),...(o.assignedToDisplayNameSnapshot?{assignedToDisplayNameSnapshot:o.assignedToDisplayNameSnapshot}:{}),createdAt:iso(o.createdAt),updatedAt:iso(o.updatedAt),...(o.closedAt?{closedAt:iso(o.closedAt)}:{}),...(o.resolvedAt?{resolvedAt:iso(o.resolvedAt)}:{}),...(o.firstPublicResponseAt?{firstPublicResponseAt:iso(o.firstPublicResponseAt)}:{}),...(o.duplicateOfProtocol?{duplicateOfProtocol:o.duplicateOfProtocol}:{}),...(o.attachedToOccurrenceId?{attachedToOccurrenceId:o.attachedToOccurrenceId}:{}),...(o.attachedToProtocol?{attachedToProtocol:o.attachedToProtocol}:{}),...(o.attachmentRelation?{attachmentRelation:o.attachmentRelation}:{}),...(o.attachmentReason?{attachmentReason:o.attachmentReason}:{}),...(o.attachedAt?{attachedAt:iso(o.attachedAt)}:{}),version:o.version,dataClassification:o.dataClassification,reopenedCount:o.reopenedCount,...(sla?{sla:dtoSla(sla,o.createdAt,now,policy),slaStatus:calculateSlaFilterStatus(o.status,sla,now)}:{}),totalOpenHours:Math.max(0,((o.closedAt??now).getTime()-o.createdAt.getTime())/3600000),effectiveBusinessHours:sla?effectiveResolutionMinutes(o.createdAt,now,sla,policyForSla(sla,policy))/60:0,timeline:visible.map(adminTimeline),publicMessages:events.filter(e=>e.visibility==='PUBLIC'&&e.eventType==='PUBLIC_MESSAGE_ADDED').map(e=>publicMessage(e,true)),internalNotes:visible.filter(e=>e.eventType==='INTERNAL_NOTE_ADDED').map(internalNote),photos:photos.map(adminPhoto)};}
export function toPublicOccurrence(o:StoredOccurrence,events:OccurrenceEventRecord[],photos:StoredPhotoMetadata[]=[]):PublicOccurrence{const pub=events.filter(e=>e.visibility==='PUBLIC');const p=photos.filter(x=>x.kind==='RESOLUTION'&&x.visibility==='PUBLIC'&&x.status==='READY');return{protocol:o.protocol,category:o.categoryNameSnapshot,location:{campusName:o.location.campusName,buildingName:o.location.buildingName,floor:o.location.floor,room:o.location.room,...(o.location.complement?{complement:o.location.complement}:{}),...(o.location.isOther===undefined?{}:{isOther:o.location.isOther}),...(o.location.otherDescription?{otherDescription:o.location.otherDescription}:{})},description:o.description,immediateRisk:o.immediateRisk,status:o.status,createdAt:iso(o.createdAt),updatedAt:iso(o.updatedAt),...(o.closedAt?{closedAt:iso(o.closedAt)}:{}),...(o.resolvedAt?{resolvedAt:iso(o.resolvedAt)}:{}),...(o.duplicateOfProtocol?{duplicateOfProtocol:o.duplicateOfProtocol}:{}),categoryAdjusted:o.reportedCategoryId!==o.categoryId,locationAdjusted:JSON.stringify(o.reportedLocation)!==JSON.stringify(o.location),timeline:pub.map(publicTimeline),publicMessages:pub.filter(e=>e.eventType==='PUBLIC_MESSAGE_ADDED').map(e=>publicMessage(e,false)),photos:p.map(publicPhoto)};}
