import type { DocumentData, DocumentSnapshot, Firestore, QueryDocumentSnapshot } from 'firebase-admin/firestore';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import type { AdminRole, AdminUser, AdminUserCreateInput, AdminUserUpdateInput, StoredAdminRole } from '../../src/models/admin';
import { isAdminRole, isLegacyAdminRole } from '../../src/models/admin';
import { hashNormalizedEmail } from '../utils/email';

export type LoginAuthorizationResult =
 | {status:'not-found'} | {status:'inactive';user:AdminUser} | {status:'uid-mismatch';user:AdminUser}
 | {status:'legacy-role';user:AdminUser} | {status:'authorized';user:AdminUser & {role:AdminRole};uidBound:boolean};
export class AdminUserConflictError extends Error{} export class AdminUserNotFoundError extends Error{} export class LastAdministratorProtectedError extends Error{}
export interface AdminUserRepository{
 authorizeLogin(normalizedEmail:string,uid:string,updateLastLogin:boolean):Promise<LoginAuthorizationResult>;list(limit:number):Promise<AdminUser[]>;getById(id:string):Promise<AdminUser|undefined>;
 create(input:AdminUserCreateInput&{normalizedEmail:string;actorId:string}):Promise<AdminUser>;update(id:string,input:AdminUserUpdateInput,actorId:string):Promise<{before:AdminUser;after:AdminUser}>;
 resolveLegacy(id:string,action:'CONVERT_TO_MANAGER'|'DEACTIVATE'|'ACTIVATE_AS_ATTENDANT',actorId:string):Promise<AdminUser>;listLegacy():Promise<AdminUser[]>;
}
function dateToIso(v:unknown):string{if(v instanceof Timestamp)return v.toDate().toISOString();if(typeof v==='string'&&!Number.isNaN(Date.parse(v)))return new Date(v).toISOString();return new Date(0).toISOString();}
function str(v:unknown):string|undefined{return typeof v==='string'&&v.trim()!==''?v:undefined;}
function role(v:unknown):StoredAdminRole{const x=typeof v==='string'||typeof v==='number'?String(v):'';return isAdminRole(x)||isLegacyAdminRole(x)?x:'Atendente';}
function fromSnapshot(s:DocumentSnapshot|QueryDocumentSnapshot|{id:string;data():DocumentData|undefined}):AdminUser{const d=s.data()??{};const r=role(d.role);return{id:s.id,email:String(d.email??''),normalizedEmail:String(d.normalizedEmail??''),...(str(d.uid)?{uid:str(d.uid)}:{}),displayName:String(d.displayName??''),role:r,...(str(d.department)?{department:str(d.department)}:{}),teamIds:Array.isArray(d.teamIds)?d.teamIds.filter((x):x is string=>typeof x==='string'):[],active:d.active===true,legacyRole:d.legacyRole===true,createdAt:dateToIso(d.createdAt),createdBy:String(d.createdBy??''),updatedAt:dateToIso(d.updatedAt),updatedBy:String(d.updatedBy??''),...(d.lastAuthorizedLoginAt===undefined?{}:{lastAuthorizedLoginAt:dateToIso(d.lastAuthorizedLoginAt)})};}
export class FirestoreAdminUserRepository implements AdminUserRepository{
 private readonly collection;public constructor(private readonly firestore:Firestore){this.collection=firestore.collection('adminUsers');}
 public async authorizeLogin(normalizedEmail:string,uid:string,updateLastLogin:boolean):Promise<LoginAuthorizationResult>{const ref=this.collection.doc(hashNormalizedEmail(normalizedEmail));return this.firestore.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)return{status:'not-found'};const user=fromSnapshot(s);if(user.normalizedEmail!==normalizedEmail)return{status:'not-found'};if(!user.active)return{status:'inactive',user};if(user.uid!==undefined&&user.uid!==uid)return{status:'uid-mismatch',user};if(user.legacyRole)return{status:'legacy-role',user};if(!isAdminRole(user.role))return{status:'legacy-role',user};const uidBound=user.uid===undefined;if(uidBound||updateLastLogin)tx.update(ref,{...(uidBound?{uid}:{}),...(updateLastLogin?{lastAuthorizedLoginAt:FieldValue.serverTimestamp()}:{})});return{status:'authorized',uidBound,user:{...user,role:user.role,uid,...(updateLastLogin?{lastAuthorizedLoginAt:new Date().toISOString()}: {})}};});}
 public async list(limit:number):Promise<AdminUser[]>{const s=await this.collection.orderBy('updatedAt','desc').limit(limit).get();return s.docs.map(fromSnapshot);}
 public async listLegacy():Promise<AdminUser[]>{const s=await this.collection.where('legacyRole','==',true).get();return s.docs.map(fromSnapshot);}
 public async getById(id:string):Promise<AdminUser|undefined>{const s=await this.collection.doc(id).get();return s.exists?fromSnapshot(s):undefined;}
 public async create(input:AdminUserCreateInput&{normalizedEmail:string;actorId:string}):Promise<AdminUser>{const id=hashNormalizedEmail(input.normalizedEmail);const ref=this.collection.doc(id);const now=new Date().toISOString();const user:AdminUser={id,email:input.normalizedEmail,normalizedEmail:input.normalizedEmail,displayName:input.displayName,role:input.role,teamIds:input.teamIds??[],active:input.active??true,legacyRole:false,createdAt:now,createdBy:input.actorId,updatedAt:now,updatedBy:input.actorId};await this.firestore.runTransaction(async tx=>{if((await tx.get(ref)).exists)throw new AdminUserConflictError('O endereço eletrônico já está autorizado.');tx.create(ref,{email:user.email,normalizedEmail:user.normalizedEmail,displayName:user.displayName,role:user.role,teamIds:user.teamIds,active:user.active,legacyRole:false,createdAt:FieldValue.serverTimestamp(),createdBy:user.createdBy,updatedAt:FieldValue.serverTimestamp(),updatedBy:user.updatedBy});});return user;}
 public async update(id:string,input:AdminUserUpdateInput,actorId:string):Promise<{before:AdminUser;after:AdminUser}>{const ref=this.collection.doc(id);return this.firestore.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new AdminUserNotFoundError('Usuário administrativo não encontrado.');const before=fromSnapshot(s);if(before.legacyRole)throw new AdminUserConflictError('Resolva explicitamente o papel legado antes de editar este usuário.');const nextRole=input.role??before.role;if(!isAdminRole(nextRole))throw new AdminUserConflictError('Papel administrativo inválido.');const nextActive=input.active??before.active;if(before.role==='Administrador'&&before.active&&(nextRole!=='Administrador'||!nextActive)){const admins=await tx.get(this.collection.where('role','==','Administrador').where('active','==',true));if(admins.size<=1)throw new LastAdministratorProtectedError('A alteração deixaria o sistema sem Administrador ativo.');}const after:AdminUser={...before,...(input.displayName===undefined?{}:{displayName:input.displayName}),role:nextRole,...(input.teamIds===undefined?{}:{teamIds:input.teamIds}),active:nextActive,updatedAt:new Date().toISOString(),updatedBy:actorId,legacyRole:false};tx.update(ref,{displayName:after.displayName,role:after.role,teamIds:after.teamIds,active:after.active,department:FieldValue.delete(),updatedAt:FieldValue.serverTimestamp(),updatedBy:actorId});return{before,after};});}
 public async resolveLegacy(id:string,action:'CONVERT_TO_MANAGER'|'DEACTIVATE'|'ACTIVATE_AS_ATTENDANT',actorId:string):Promise<AdminUser>{const ref=this.collection.doc(id);return this.firestore.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new AdminUserNotFoundError();const before=fromSnapshot(s);if(!before.legacyRole)throw new AdminUserConflictError('O usuário não possui papel legado.');const after:AdminUser={...before,role:action==='CONVERT_TO_MANAGER'?'Gestor':action==='ACTIVATE_AS_ATTENDANT'?'Atendente':before.role,active:action==='DEACTIVATE'?false:true,legacyRole:action==='DEACTIVATE',updatedAt:new Date().toISOString(),updatedBy:actorId};tx.update(ref,{...(action==='CONVERT_TO_MANAGER'?{role:'Gestor',legacyRole:false,active:true}:action==='ACTIVATE_AS_ATTENDANT'?{role:'Atendente',legacyRole:false,active:true}:{active:false}),updatedAt:FieldValue.serverTimestamp(),updatedBy:actorId});return after;});}
}

/** Repositório em memória destinado exclusivamente aos testes automatizados. */
export class InMemoryAdminUserRepository implements AdminUserRepository {
  private readonly users = new Map<string, AdminUser>();
  public constructor(seed: AdminUser[] = []) { for (const user of seed) this.users.set(user.id, structuredClone(user)); }
  public async authorizeLogin(normalizedEmail:string,uid:string,updateLastLogin:boolean):Promise<LoginAuthorizationResult>{
    await Promise.resolve(); const id=hashNormalizedEmail(normalizedEmail); const user=this.users.get(id);
    if(!user||user.normalizedEmail!==normalizedEmail)return{status:'not-found'};
    if(!user.active)return{status:'inactive',user:structuredClone(user)};
    if(user.uid!==undefined&&user.uid!==uid)return{status:'uid-mismatch',user:structuredClone(user)};
    if(user.legacyRole)return{status:'legacy-role',user:structuredClone(user)};
    if(!isAdminRole(user.role))return{status:'legacy-role',user:structuredClone(user)};
    const uidBound=user.uid===undefined; const updated:AdminUser={...user,uid,...(updateLastLogin?{lastAuthorizedLoginAt:new Date().toISOString()}:{})}; this.users.set(id,updated);
    return{status:'authorized',user:{...structuredClone(updated),role:updated.role},uidBound};
  }
  public async list(limit:number):Promise<AdminUser[]>{await Promise.resolve();return[...this.users.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,limit).map(x=>structuredClone(x));}
  public async listLegacy():Promise<AdminUser[]>{await Promise.resolve();return[...this.users.values()].filter(x=>x.legacyRole).map(x=>structuredClone(x));}
  public async getById(id:string):Promise<AdminUser|undefined>{await Promise.resolve();const x=this.users.get(id);return x?structuredClone(x):undefined;}
  public async create(input:AdminUserCreateInput&{normalizedEmail:string;actorId:string}):Promise<AdminUser>{await Promise.resolve();const id=hashNormalizedEmail(input.normalizedEmail);if(this.users.has(id))throw new AdminUserConflictError('O endereço eletrônico já está autorizado.');const now=new Date().toISOString();const user:AdminUser={id,email:input.normalizedEmail,normalizedEmail:input.normalizedEmail,displayName:input.displayName,role:input.role,teamIds:input.teamIds??[],active:input.active??true,legacyRole:false,createdAt:now,createdBy:input.actorId,updatedAt:now,updatedBy:input.actorId};this.users.set(id,user);return structuredClone(user);}
  public async update(id:string,input:AdminUserUpdateInput,actorId:string):Promise<{before:AdminUser;after:AdminUser}>{await Promise.resolve();const before=this.users.get(id);if(!before)throw new AdminUserNotFoundError();if(before.legacyRole)throw new AdminUserConflictError('Resolva explicitamente o papel legado.');const nextRole=input.role??before.role;if(!isAdminRole(nextRole))throw new AdminUserConflictError();const nextActive=input.active??before.active;if(before.role==='Administrador'&&before.active&&(nextRole!=='Administrador'||!nextActive)&&[...this.users.values()].filter(x=>x.role==='Administrador'&&x.active).length<=1)throw new LastAdministratorProtectedError();const after:AdminUser={...before,...(input.displayName===undefined?{}:{displayName:input.displayName}),role:nextRole,...(input.teamIds===undefined?{}:{teamIds:input.teamIds}),active:nextActive,legacyRole:false,updatedAt:new Date().toISOString(),updatedBy:actorId};delete after.department;this.users.set(id,after);return{before:structuredClone(before),after:structuredClone(after)};}
  public async resolveLegacy(id:string,action:'CONVERT_TO_MANAGER'|'DEACTIVATE'|'ACTIVATE_AS_ATTENDANT',actorId:string):Promise<AdminUser>{await Promise.resolve();const before=this.users.get(id);if(!before)throw new AdminUserNotFoundError();if(!before.legacyRole)throw new AdminUserConflictError();const after:AdminUser={...before,role:action==='CONVERT_TO_MANAGER'?'Gestor':action==='ACTIVATE_AS_ATTENDANT'?'Atendente':before.role,active:action==='DEACTIVATE'?false:true,legacyRole:action==='DEACTIVATE',updatedAt:new Date().toISOString(),updatedBy:actorId};this.users.set(id,after);return structuredClone(after);}
}
