import type { DocumentSnapshot, Firestore } from 'firebase-admin/firestore';
import { FieldValue } from 'firebase-admin/firestore';
import type { BuildingLocation, CampusLocation, RoomLocation } from '../../src/models/config';
import type { LocationDetail, LocationSelectionInput } from '../../src/models/occurrence';

function parseLocationDocument(snapshot:DocumentSnapshot):CampusLocation{const d=snapshot.data()??{};return{id:snapshot.id,campusName:String(d.campusName??''),buildings:Array.isArray(d.buildings)?d.buildings as CampusLocation['buildings']:[],provisional:d.provisional===true,version:Number(d.version??1)};}
export class LocationVersionConflictError extends Error {}
export interface LocationRepository {
  list():Promise<CampusLocation[]>; getCampus(id:string):Promise<CampusLocation|undefined>; resolveSnapshot(input:LocationSelectionInput):Promise<LocationDetail|undefined>;
  seed(items:CampusLocation[],updatedBy:string):Promise<void>;
  addArea(campusId:string,area:BuildingLocation,expectedVersion:number,updatedBy:string):Promise<CampusLocation>;
  updateArea(campusId:string,areaId:string,input:{name?:string;active?:boolean;sortOrder?:number;expectedVersion:number},updatedBy:string):Promise<CampusLocation>;
  addEnvironment(campusId:string,areaId:string,room:RoomLocation,expectedVersion:number,updatedBy:string):Promise<CampusLocation>;
  updateEnvironment(campusId:string,areaId:string,roomId:string,input:{name?:string;active?:boolean;sortOrder?:number;expectedVersion:number},updatedBy:string):Promise<CampusLocation>;
}
export class FirestoreLocationRepository implements LocationRepository{
  private readonly collection; public constructor(private readonly firestore:Firestore){this.collection=firestore.collection('locations');}
  public async list():Promise<CampusLocation[]>{const s=await this.collection.get();return s.docs.map(parseLocationDocument).sort((a,b)=>a.campusName.localeCompare(b.campusName,'pt-BR'));}
  public async getCampus(id:string):Promise<CampusLocation|undefined>{const s=await this.collection.doc(id).get();return s.exists?parseLocationDocument(s):undefined;}
  public async resolveSnapshot(input:LocationSelectionInput):Promise<LocationDetail|undefined>{const campus=await this.getCampus(input.campusId);if(campus===undefined)return undefined;const building=campus.buildings.find(x=>x.id===input.buildingId&&x.active!==false);const floor=building?.floors.find(x=>x.id===input.floorId);const room=floor?.rooms.find(x=>x.id===input.roomId&&x.active!==false);if(building===undefined||floor===undefined||room===undefined)return undefined;return{campusId:campus.id,campusName:campus.campusName,buildingId:building.id,buildingName:building.name,floorId:floor.id,floor:floor.name,roomId:room.id,room:room.name,...(input.complement?{complement:input.complement}:{}),...(input.isOther===undefined?{}:{isOther:input.isOther}),...(input.otherDescription?{otherDescription:input.otherDescription}:{})};}
  public async seed(items:CampusLocation[],updatedBy:string):Promise<void>{for(const item of items){const ref=this.collection.doc(item.id);const existing=await ref.get();if(!existing.exists){await ref.create({campusName:item.campusName,buildings:item.buildings,provisional:false,schemaVersion:2,version:1,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp(),updatedBy});continue;}const current=parseLocationDocument(existing);let changed=false;const buildings=current.buildings.map(b=>structuredClone(b));for(const seedArea of item.buildings){const area=buildings.find(b=>b.id===seedArea.id);if(area===undefined){buildings.push(structuredClone(seedArea));changed=true;continue;}const targetFloor=area.floors[0];const seedFloor=seedArea.floors[0];if(targetFloor===undefined||seedFloor===undefined)continue;for(const seedRoom of seedFloor.rooms){if(!targetFloor.rooms.some(r=>r.id===seedRoom.id)){targetFloor.rooms.push(structuredClone(seedRoom));changed=true;}}}if(changed)await ref.update({buildings,version:(current.version??1)+1,updatedAt:FieldValue.serverTimestamp(),updatedBy});}}
  private async mutate(campusId:string,expectedVersion:number,updatedBy:string,fn:(c:CampusLocation)=>void):Promise<CampusLocation>{const ref=this.collection.doc(campusId);return this.firestore.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new Error('LOCATION_NOT_FOUND');const c=parseLocationDocument(s);if((c.version??1)!==expectedVersion)throw new LocationVersionConflictError();fn(c);c.version=(c.version??1)+1;tx.update(ref,{buildings:c.buildings,version:c.version,updatedAt:FieldValue.serverTimestamp(),updatedBy});return c;});}
  public addArea(campusId:string,area:BuildingLocation,expectedVersion:number,updatedBy:string):Promise<CampusLocation>{return this.mutate(campusId,expectedVersion,updatedBy,c=>{if(c.buildings.some(x=>x.id===area.id))throw new Error('AREA_EXISTS');c.buildings.push(area);});}
  public updateArea(campusId:string,areaId:string,input:{name?:string;active?:boolean;sortOrder?:number;expectedVersion:number},updatedBy:string):Promise<CampusLocation>{return this.mutate(campusId,input.expectedVersion,updatedBy,c=>{const a=c.buildings.find(x=>x.id===areaId);if(a===undefined)throw new Error('AREA_NOT_FOUND');if(input.name!==undefined)a.name=input.name;if(input.active!==undefined)a.active=input.active;if(input.sortOrder!==undefined)a.sortOrder=input.sortOrder;});}
  public addEnvironment(campusId:string,areaId:string,room:RoomLocation,expectedVersion:number,updatedBy:string):Promise<CampusLocation>{return this.mutate(campusId,expectedVersion,updatedBy,c=>{const a=c.buildings.find(x=>x.id===areaId);const f=a?.floors[0];if(a===undefined||f===undefined)throw new Error('AREA_NOT_FOUND');if(f.rooms.some(x=>x.id===room.id))throw new Error('ROOM_EXISTS');f.rooms.push(room);});}
  public updateEnvironment(campusId:string,areaId:string,roomId:string,input:{name?:string;active?:boolean;sortOrder?:number;expectedVersion:number},updatedBy:string):Promise<CampusLocation>{return this.mutate(campusId,input.expectedVersion,updatedBy,c=>{const r=c.buildings.find(x=>x.id===areaId)?.floors[0]?.rooms.find(x=>x.id===roomId);if(r===undefined)throw new Error('ROOM_NOT_FOUND');if(input.name!==undefined)r.name=input.name;if(input.active!==undefined)r.active=input.active;if(input.sortOrder!==undefined)r.sortOrder=input.sortOrder;});}
}
