import type { CollectionReference, DocumentData, DocumentSnapshot, Firestore, Query, QueryDocumentSnapshot } from 'firebase-admin/firestore';
import { FieldPath, Filter, Timestamp } from 'firebase-admin/firestore';
import type { AuthorizedAdminProfile } from '../../src/models/admin';
import type { DataClassification, OccurrenceFilterOptions, OccurrencePriority, OccurrenceSort, OccurrenceStatus } from '../../src/models/occurrence';
import { PRIORITY_RANK } from '../../src/models/occurrence';
import { formatProtocol } from '../../src/utils/protocol';
import { normalizeSearchKeyword } from '../../src/utils/textNormalization';
import { zonedLocalToDate } from '../domain/businessTime';
import { createOccurrenceNotificationItems } from '../domain/notificationOutbox';
import type { NewOccurrenceEvent, NewOccurrenceRecord, StoredOccurrence, StoredOccurrenceSla } from '../models/occurrenceDomain';
import type { StoredPhotoMetadata } from '../models/photoDomain';
import { eventToFirestore } from './occurrenceEventRepository';
import { photoMetadataToFirestore } from './photoMetadataRepository';
import type { NotificationOutboxItem } from '../models/notificationDomain';
import { notificationToFirestore } from './notificationOutboxRepository';
import { FirestoreProtocolCounterRepository } from './protocolCounterRepository';

function optionalString(v:unknown):string|undefined{return typeof v==='string'&&v.trim()!==''?v:undefined;}
function toDate(v:unknown):Date{if(v instanceof Timestamp)return v.toDate();if(v instanceof Date)return v;if(typeof v==='string'&&!Number.isNaN(Date.parse(v)))return new Date(v);throw new Error('Timestamp inválido no documento de ocorrência.');}
function optionalDate(v:unknown):Date|undefined{return v===undefined||v===null?undefined:toDate(v);}
function parseSla(v:unknown):StoredOccurrenceSla|undefined{if(v===undefined||v===null||typeof v!=='object')return undefined;const d=v as Record<string,unknown>;if(d.firstResponseDueAt===undefined||d.resolutionDueAt===undefined||d.resolutionNearDueAt===undefined)return undefined;return{schemaVersion:1,policyVersion:typeof d.policyVersion==='string'||typeof d.policyVersion==='number'?String(d.policyVersion):'',firstResponseTargetBusinessMinutes:Number(d.firstResponseTargetBusinessMinutes??0),firstResponseDueAt:toDate(d.firstResponseDueAt),...(optionalDate(d.firstResponseAt)?{firstResponseAt:optionalDate(d.firstResponseAt)}:{}),...(d.firstResponseOutcome==='ON_TIME'||d.firstResponseOutcome==='BREACHED'?{firstResponseOutcome:d.firstResponseOutcome}:{}),resolutionBaseBusinessMinutes:Number(d.resolutionBaseBusinessMinutes??0),priorityMultiplier:Number(d.priorityMultiplier??1),resolutionTargetBusinessMinutes:Number(d.resolutionTargetBusinessMinutes??0),resolutionDueAt:toDate(d.resolutionDueAt),resolutionNearDueAt:toDate(d.resolutionNearDueAt),resolutionPaused:d.resolutionPaused===true,...(optionalDate(d.resolutionPauseStartedAt)?{resolutionPauseStartedAt:optionalDate(d.resolutionPauseStartedAt)}:{}),accumulatedPausedBusinessMinutes:Number(d.accumulatedPausedBusinessMinutes??0),...(optionalDate(d.completedAt)?{completedAt:optionalDate(d.completedAt)}:{}),...(d.resolutionOutcome==='ON_TIME'||d.resolutionOutcome==='BREACHED'?{resolutionOutcome:d.resolutionOutcome}:{}),calendarSnapshotId:typeof d.calendarSnapshotId==='string'||typeof d.calendarSnapshotId==='number'?String(d.calendarSnapshotId):'default',...(d.calendarSnapshot&&typeof d.calendarSnapshot==='object'?{calendarSnapshot:d.calendarSnapshot as StoredOccurrenceSla['calendarSnapshot']}:{ }),...(d.legacyAssessment==='CALCULATED'||d.legacyAssessment==='ESTIMATED'||d.legacyAssessment==='UNAVAILABLE'?{legacyAssessment:d.legacyAssessment}:{})};}
function snapshotToOccurrence(s:DocumentSnapshot|QueryDocumentSnapshot|{id:string;data():DocumentData|undefined}):StoredOccurrence{const d=s.data()??{};const location=d.location as StoredOccurrence['location'];const reported=(d.reportedLocation??location) as StoredOccurrence['reportedLocation'];const priority=d.priority as OccurrencePriority;const sla=parseSla(d.sla);return{id:s.id,schemaVersion:2,protocol:String(d.protocol??''),trackingKeyHash:String(d.trackingKeyHash??''),trackingKeySalt:String(d.trackingKeySalt??''),reportedCategoryId:String(d.reportedCategoryId??d.categoryId??''),reportedCategoryNameSnapshot:String(d.reportedCategoryNameSnapshot??d.categoryNameSnapshot??''),categoryId:String(d.categoryId??''),categoryNameSnapshot:String(d.categoryNameSnapshot??''),reportedLocation:reported,location,description:String(d.description??''),immediateRisk:d.immediateRisk===true,status:d.status as OccurrenceStatus,priority,priorityRank:Number(d.priorityRank??PRIORITY_RANK[priority]??4),...(optionalString(d.assignedTeamId)?{assignedTeamId:optionalString(d.assignedTeamId)}:{}),...(optionalString(d.assignedTeamNameSnapshot)?{assignedTeamNameSnapshot:optionalString(d.assignedTeamNameSnapshot)}:{}),...(optionalString(d.assignedToAdminUserId)?{assignedToAdminUserId:optionalString(d.assignedToAdminUserId)}:{}),...(optionalString(d.assignedToDisplayNameSnapshot)?{assignedToDisplayNameSnapshot:optionalString(d.assignedToDisplayNameSnapshot)}:{}),...(optionalString(d.duplicateOfOccurrenceId)?{duplicateOfOccurrenceId:optionalString(d.duplicateOfOccurrenceId)}:{}),...(optionalString(d.duplicateOfProtocol)?{duplicateOfProtocol:optionalString(d.duplicateOfProtocol)}:{}),...(optionalString(d.attachedToOccurrenceId)?{attachedToOccurrenceId:optionalString(d.attachedToOccurrenceId)}:{}),...(optionalString(d.attachedToProtocol)?{attachedToProtocol:optionalString(d.attachedToProtocol)}:{}),...(d.attachmentRelation==='DUPLICATE'||d.attachmentRelation==='SIMILAR'?{attachmentRelation:d.attachmentRelation}:{}),...(optionalString(d.attachmentReason)?{attachmentReason:optionalString(d.attachmentReason)}:{}),...(optionalDate(d.attachedAt)?{attachedAt:optionalDate(d.attachedAt)}:{}),...(optionalString(d.attachedByAdminUserId)?{attachedByAdminUserId:optionalString(d.attachedByAdminUserId)}:{}),createdAt:toDate(d.createdAt),updatedAt:toDate(d.updatedAt),...(optionalDate(d.closedAt)?{closedAt:optionalDate(d.closedAt)}:{}),...(optionalDate(d.resolvedAt)?{resolvedAt:optionalDate(d.resolvedAt)}:{}),...(optionalDate(d.firstPublicResponseAt)?{firstPublicResponseAt:optionalDate(d.firstPublicResponseAt)}:{}),version:Number(d.version??1),dataClassification:d.dataClassification==='TEST'?'TEST':'REAL',reopenedCount:Number(d.reopenedCount??0),...(optionalDate(d.lastReopenedAt)?{lastReopenedAt:optionalDate(d.lastReopenedAt)}:{}),hasPhoto:d.hasPhoto===true,searchTokens:Array.isArray(d.searchTokens)?d.searchTokens.filter((x):x is string=>typeof x==='string'):[],...(sla===undefined?{}:{sla})};}
function ts(v:Date):Timestamp{return Timestamp.fromDate(v);}
function slaToFirestore(sla:StoredOccurrenceSla):DocumentData{return{schemaVersion:1,policyVersion:sla.policyVersion,firstResponseTargetBusinessMinutes:sla.firstResponseTargetBusinessMinutes,firstResponseDueAt:ts(sla.firstResponseDueAt),...(sla.firstResponseAt?{firstResponseAt:ts(sla.firstResponseAt)}:{}),...(sla.firstResponseOutcome?{firstResponseOutcome:sla.firstResponseOutcome}:{}),resolutionBaseBusinessMinutes:sla.resolutionBaseBusinessMinutes,priorityMultiplier:sla.priorityMultiplier,resolutionTargetBusinessMinutes:sla.resolutionTargetBusinessMinutes,resolutionDueAt:ts(sla.resolutionDueAt),resolutionNearDueAt:ts(sla.resolutionNearDueAt),resolutionPaused:sla.resolutionPaused,...(sla.resolutionPauseStartedAt?{resolutionPauseStartedAt:ts(sla.resolutionPauseStartedAt)}:{}),accumulatedPausedBusinessMinutes:sla.accumulatedPausedBusinessMinutes,...(sla.completedAt?{completedAt:ts(sla.completedAt)}:{}),...(sla.resolutionOutcome?{resolutionOutcome:sla.resolutionOutcome}:{}),calendarSnapshotId:sla.calendarSnapshotId,...(sla.calendarSnapshot?{calendarSnapshot:sla.calendarSnapshot}:{}),...(sla.legacyAssessment?{legacyAssessment:sla.legacyAssessment}:{})};}
export function occurrenceToFirestore(o:StoredOccurrence):DocumentData{return{schemaVersion:2,protocol:o.protocol,trackingKeyHash:o.trackingKeyHash,trackingKeySalt:o.trackingKeySalt,reportedCategoryId:o.reportedCategoryId,reportedCategoryNameSnapshot:o.reportedCategoryNameSnapshot,categoryId:o.categoryId,categoryNameSnapshot:o.categoryNameSnapshot,reportedLocation:o.reportedLocation,location:o.location,description:o.description,immediateRisk:o.immediateRisk,status:o.status,priority:o.priority,priorityRank:o.priorityRank,hasTeam:o.assignedTeamId!==undefined,hasResponsible:o.assignedToAdminUserId!==undefined,hasPhoto:o.hasPhoto,isClosed:o.closedAt!==undefined,reopened:o.reopenedCount>0,...(o.assignedTeamId?{assignedTeamId:o.assignedTeamId}:{}),...(o.assignedTeamNameSnapshot?{assignedTeamNameSnapshot:o.assignedTeamNameSnapshot}:{}),...(o.assignedToAdminUserId?{assignedToAdminUserId:o.assignedToAdminUserId}:{}),...(o.assignedToDisplayNameSnapshot?{assignedToDisplayNameSnapshot:o.assignedToDisplayNameSnapshot}:{}),...(o.duplicateOfOccurrenceId?{duplicateOfOccurrenceId:o.duplicateOfOccurrenceId}:{}),...(o.duplicateOfProtocol?{duplicateOfProtocol:o.duplicateOfProtocol}:{}),...(o.attachedToOccurrenceId?{attachedToOccurrenceId:o.attachedToOccurrenceId}:{}),...(o.attachedToProtocol?{attachedToProtocol:o.attachedToProtocol}:{}),...(o.attachmentRelation?{attachmentRelation:o.attachmentRelation}:{}),...(o.attachmentReason?{attachmentReason:o.attachmentReason}:{}),...(o.attachedAt?{attachedAt:ts(o.attachedAt)}:{}),...(o.attachedByAdminUserId?{attachedByAdminUserId:o.attachedByAdminUserId}:{}),createdAt:ts(o.createdAt),updatedAt:ts(o.updatedAt),...(o.closedAt?{closedAt:ts(o.closedAt)}:{}),...(o.resolvedAt?{resolvedAt:ts(o.resolvedAt)}:{}),...(o.firstPublicResponseAt?{firstPublicResponseAt:ts(o.firstPublicResponseAt)}:{}),version:o.version,dataClassification:o.dataClassification,reopenedCount:o.reopenedCount,...(o.lastReopenedAt?{lastReopenedAt:ts(o.lastReopenedAt)}:{}),searchTokens:o.searchTokens,...(o.sla?{sla:slaToFirestore(o.sla)}:{})};}
function synchronizeOperationalState(target:StoredOccurrence,source:StoredOccurrence):StoredOccurrence{const out:StoredOccurrence={...target,status:source.status,priority:source.priority,priorityRank:source.priorityRank,updatedAt:source.updatedAt,version:target.version+1,dataClassification:source.dataClassification,reopenedCount:source.reopenedCount,hasPhoto:target.hasPhoto,searchTokens:target.searchTokens,...(source.sla?{sla:structuredClone(source.sla)}:{})};if(!source.sla)delete out.sla;if(source.assignedTeamId){out.assignedTeamId=source.assignedTeamId;out.assignedTeamNameSnapshot=source.assignedTeamNameSnapshot;}else{delete out.assignedTeamId;delete out.assignedTeamNameSnapshot;}if(source.assignedToAdminUserId){out.assignedToAdminUserId=source.assignedToAdminUserId;out.assignedToDisplayNameSnapshot=source.assignedToDisplayNameSnapshot;}else{delete out.assignedToAdminUserId;delete out.assignedToDisplayNameSnapshot;}if(source.closedAt)out.closedAt=source.closedAt;else delete out.closedAt;if(source.resolvedAt)out.resolvedAt=source.resolvedAt;else delete out.resolvedAt;if(source.firstPublicResponseAt)out.firstPublicResponseAt=source.firstPublicResponseAt;else delete out.firstPublicResponseAt;if(source.lastReopenedAt)out.lastReopenedAt=source.lastReopenedAt;else delete out.lastReopenedAt;return out;}
function encodeCursor(values:unknown[]):string{return Buffer.from(JSON.stringify(values.map(v=>v instanceof Timestamp?{date:v.toDate().toISOString()}:v instanceof Date?{date:v.toISOString()}:v)),'utf8').toString('base64url');}
function decodeCursor(value:string):unknown[]{const arr=JSON.parse(Buffer.from(value,'base64url').toString('utf8')) as unknown[];return arr.map(v=>typeof v==='object'&&v!==null&&'date' in v?Timestamp.fromDate(new Date(String((v as {date:unknown}).date))):v);}
type OrderField=[string,'asc'|'desc'];
function baseOrdering(sort:OccurrenceSort|undefined):OrderField[]{switch(sort){case'newest':return[['createdAt','desc'],['__name__','desc']];case'oldest':return[['createdAt','asc'],['__name__','asc']];case'protocol':return[['protocol','asc'],['__name__','asc']];case'sla':return[['sla.resolutionDueAt','asc'],['createdAt','asc'],['__name__','asc']];case'priority':case'operational':default:return[['priorityRank','asc'],['sla.resolutionDueAt','asc'],['createdAt','asc'],['__name__','asc']];}}
function inequalityOrdering(filters:OccurrenceFilterOptions):OrderField[]{const fields:OrderField[]=[];const add=(field:string,dir:'asc'|'desc'='asc'):void=>{if(!fields.some(([existing])=>existing===field))fields.push([field,dir]);};if(filters.startDate||filters.endDate)add('createdAt',filters.sort==='newest'?'desc':'asc');if(filters.closedStartDate||filters.closedEndDate)add('closedAt');if(filters.reopenedStartDate||filters.reopenedEndDate)add('lastReopenedAt');if(filters.slaStatus==='BREACHED')add('sla.resolutionDueAt');if(filters.slaStatus==='NEAR_DUE'){add('sla.resolutionDueAt');add('sla.resolutionNearDueAt');}if(filters.slaStatus==='ON_TIME')add('sla.resolutionNearDueAt');return fields;}
function ordering(sort:OccurrenceSort|undefined,filters:OccurrenceFilterOptions={}):OrderField[]{const ranges=inequalityOrdering(filters);const desired=baseOrdering(sort);if(ranges.length===0)return desired;const result:OrderField[]=[...ranges];for(const order of desired){if(!result.some(([field])=>field===order[0]))result.push(order);}if(!result.some(([field])=>field==='__name__'))result.push(['__name__',result.at(-1)?.[1]??'asc']);return result;}
function cursorValues(last:QueryDocumentSnapshot,orders:OrderField[]):unknown[]{return orders.map(([field])=>field==='__name__'?last.id:(last.get(field) as unknown));}
function applyFilters(q:Query<DocumentData>,f:OccurrenceFilterOptions,now:Date):Query<DocumentData>{if(f.protocol)q=q.where('protocol','==',f.protocol.trim().toUpperCase());if(f.keyword){const token=normalizeSearchKeyword(f.keyword);if(token)q=q.where('searchTokens','array-contains',token);}if(f.category)q=q.where('categoryId','==',f.category);if(f.areaId)q=q.where('location.buildingId','==',f.areaId);if(f.environmentId)q=q.where('location.roomId','==',f.environmentId);if(f.status&&f.status!=='TODAS')q=q.where('status','==',f.status);if(f.priority&&f.priority!=='TODAS')q=q.where('priority','==',f.priority);if(f.assignedTeamId)q=q.where('assignedTeamId','==',f.assignedTeamId);if(f.assignedToAdminUserId)q=q.where('assignedToAdminUserId','==',f.assignedToAdminUserId);if(f.immediateRisk)q=q.where('immediateRisk','==',f.immediateRisk==='true');if(f.withoutTeam)q=q.where('hasTeam','==',false);if(f.withoutRouting)q=q.where(Filter.or(Filter.where('hasTeam','==',false),Filter.where('hasResponsible','==',false)));if(f.criticalPriority)q=q.where('priority','in',['Urgente','Emergencial']);if(f.awaitingAction)q=q.where('status','in',['Aguardando material','Aguardando contratação ou serviço externo']);if(f.withoutResponsible)q=q.where('hasResponsible','==',false);if(f.withPhoto)q=q.where('hasPhoto','==',true);if(f.withoutPhoto)q=q.where('hasPhoto','==',false);if(f.reopened)q=q.where('reopened','==',true);if(f.reopenedStartDate)q=q.where('lastReopenedAt','>=',Timestamp.fromDate(zonedLocalToDate(f.reopenedStartDate,'00:00','America/Sao_Paulo')));if(f.reopenedEndDate)q=q.where('lastReopenedAt','<=',Timestamp.fromDate(new Date(zonedLocalToDate(f.reopenedEndDate,'23:59','America/Sao_Paulo').getTime()+59_999)));if(f.dataClassification)q=q.where('dataClassification','==',f.dataClassification);if(f.startDate)q=q.where('createdAt','>=',Timestamp.fromDate(zonedLocalToDate(f.startDate,'00:00','America/Sao_Paulo')));if(f.endDate)q=q.where('createdAt','<=',Timestamp.fromDate(new Date(zonedLocalToDate(f.endDate,'23:59','America/Sao_Paulo').getTime()+59_999)));if(f.closedStartDate)q=q.where('closedAt','>=',Timestamp.fromDate(zonedLocalToDate(f.closedStartDate,'00:00','America/Sao_Paulo')));if(f.closedEndDate)q=q.where('closedAt','<=',Timestamp.fromDate(new Date(zonedLocalToDate(f.closedEndDate,'23:59','America/Sao_Paulo').getTime()+59_999)));if(f.slaStatus==='PAUSED')q=q.where('sla.resolutionPaused','==',true);if(f.slaStatus==='COMPLETED')q=q.where('isClosed','==',true);if(f.slaStatus==='BREACHED')q=q.where('isClosed','==',false).where('sla.resolutionPaused','==',false).where('sla.resolutionDueAt','<',ts(now));if(f.slaStatus==='NEAR_DUE')q=q.where('isClosed','==',false).where('sla.resolutionPaused','==',false).where('sla.resolutionNearDueAt','<=',ts(now)).where('sla.resolutionDueAt','>=',ts(now));if(f.slaStatus==='ON_TIME')q=q.where('isClosed','==',false).where('sla.resolutionPaused','==',false).where('sla.resolutionNearDueAt','>',ts(now));return q;}
export class OccurrenceVersionConflictError extends Error{} export class DuplicateCycleError extends Error{} export class DuplicateTargetNotFoundError extends Error{} export class AttachmentGroupTooLargeError extends Error{}
export interface OccurrenceCountFilter{assignedToAdminUserId?:string;assignedTeamId?:string;status?:OccurrenceStatus;statuses?:OccurrenceStatus[];priorities?:OccurrencePriority[];createdAtFrom?:Date;createdAtTo?:Date;resolvedAtFrom?:Date;resolvedAtTo?:Date;closedAtFrom?:Date;closedAtTo?:Date;isClosed?:boolean;hasTeam?:boolean;hasResponsible?:boolean;slaBreachedAt?:Date;dataClassification?:DataClassification;}
export interface OccurrenceOperationalPropagation{enabled:boolean;events:NewOccurrenceEvent[];}
export interface OccurrenceCreationPersistenceOptions{occurrenceId?:string;photos?:StoredPhotoMetadata[];notificationRecipients?:string[];notificationProvider?:'resend'|'ews';} export interface OccurrencePhotoMutations{create?:StoredPhotoMetadata[];update?:StoredPhotoMetadata[];}
export interface OccurrenceRepository{
 createWithProtocol(input:NewOccurrenceRecord,prefix:string,events:NewOccurrenceEvent[],options?:OccurrenceCreationPersistenceOptions):Promise<StoredOccurrence>;getById(id:string):Promise<StoredOccurrence|undefined>;findByProtocol(protocol:string):Promise<StoredOccurrence|undefined>;
 list(filters:OccurrenceFilterOptions,user:AuthorizedAdminProfile):Promise<{items:StoredOccurrence[];limit:number;hasMore:boolean;nextCursor?:string}>;
 listForAnalytics(filters:OccurrenceFilterOptions,max:number):Promise<{items:StoredOccurrence[];truncated:boolean;total:number}>;
 listForExport(filters:OccurrenceFilterOptions,max:number):Promise<{items:StoredOccurrence[];truncated:boolean}>;
 countFiltered(filters:OccurrenceFilterOptions):Promise<number>;
 listAttachmentGroup(occurrenceId:string):Promise<StoredOccurrence[]>;
 updateWithEvents(next:StoredOccurrence,expectedVersion:number,events:NewOccurrenceEvent[],photoMutations?:OccurrencePhotoMutations,notificationItems?:NotificationOutboxItem[],propagation?:OccurrenceOperationalPropagation):Promise<StoredOccurrence>;
 wouldCreateDuplicateCycle(sourceId:string,targetId:string):Promise<boolean>;count(filter:OccurrenceCountFilter):Promise<number>;
 isLocationReferenced(buildingId:string,roomId?:string):Promise<boolean>;
 deleteOccurrenceTree(id:string):Promise<void>;
}
export class FirestoreOccurrenceRepository implements OccurrenceRepository{
 private readonly collection: CollectionReference<DocumentData>;
 private readonly counters: FirestoreProtocolCounterRepository;
  public constructor(private readonly firestore: Firestore) {
    this.collection = firestore.collection('occurrences');
    this.counters = new FirestoreProtocolCounterRepository(firestore);
  }
  public async createWithProtocol(input:NewOccurrenceRecord,prefix:string,events:NewOccurrenceEvent[],options:OccurrenceCreationPersistenceOptions={}):Promise<StoredOccurrence>{const ref=options.occurrenceId?this.collection.doc(options.occurrenceId):this.collection.doc();const now=events[0]?.createdAt??new Date();const year=Number(new Intl.DateTimeFormat('en',{year:'numeric',timeZone:'America/Sao_Paulo'}).format(now));let created:StoredOccurrence|undefined;await this.firestore.runTransaction(async tx=>{const sequence=await this.counters.getNextSequence(tx,year);const protocol=formatProtocol(prefix,year,sequence);if(!(await tx.get(this.collection.where('protocol','==',protocol).limit(1))).empty)throw new Error('PROTOCOL_DUPLICATE');created={id:ref.id,schemaVersion:2,protocol,trackingKeyHash:input.trackingKeyHash,trackingKeySalt:input.trackingKeySalt,reportedCategoryId:input.categoryId,reportedCategoryNameSnapshot:input.categoryNameSnapshot,categoryId:input.categoryId,categoryNameSnapshot:input.categoryNameSnapshot,reportedLocation:structuredClone(input.location),location:structuredClone(input.location),description:input.description,immediateRisk:input.immediateRisk,status:'Recebida',priority:input.priority,priorityRank:PRIORITY_RANK[input.priority],createdAt:now,updatedAt:now,version:1,dataClassification:input.dataClassification,reopenedCount:0,hasPhoto:(options.photos?.length??0)>0,searchTokens:input.searchTokens,sla:input.sla,...(input.assignedTeamId?{assignedTeamId:input.assignedTeamId,assignedTeamNameSnapshot:input.assignedTeamNameSnapshot}:{})};this.counters.setSequence(tx,year,sequence,now);tx.create(ref,occurrenceToFirestore(created));for(const e of events)tx.create(ref.collection('events').doc(),eventToFirestore(e));for(const p of options.photos??[])tx.create(ref.collection('photos').doc(p.id),photoMetadataToFirestore(p));for(const notification of createOccurrenceNotificationItems(created,options.notificationRecipients??[],now,options.notificationProvider??'ews'))tx.create(this.firestore.collection('notificationOutbox').doc(notification.id),notificationToFirestore(notification));});if(!created)throw new Error('CREATE_FAILED');return structuredClone(created);}
 public async getById(id:string):Promise<StoredOccurrence|undefined>{const s=await this.collection.doc(id).get();return s.exists?snapshotToOccurrence(s):undefined;}
 public async findByProtocol(protocol:string):Promise<StoredOccurrence|undefined>{const s=await this.collection.where('protocol','==',protocol.trim().toUpperCase()).limit(1).get();return s.docs[0]?snapshotToOccurrence(s.docs[0]):undefined;}
 public async list(filters:OccurrenceFilterOptions,_user:AuthorizedAdminProfile):Promise<{items:StoredOccurrence[];limit:number;hasMore:boolean;nextCursor?:string}>{void _user;const limit=filters.pageSize??25;let q:Query<DocumentData>=applyFilters(this.collection,filters,new Date());const orders=ordering(filters.sort,filters);for(const [field,dir] of orders)q=q.orderBy(field==='__name__'?FieldPath.documentId():field,dir);if(filters.cursor)q=q.startAfter(...decodeCursor(filters.cursor));const s=await q.limit(limit+1).get();const docs=s.docs.slice(0,limit);const items=docs.map(snapshotToOccurrence);const last=docs.at(-1);let nextCursor:string|undefined;if(last&&s.size>limit){nextCursor=encodeCursor(cursorValues(last,orders));}return{items,limit,hasMore:s.size>limit,...(nextCursor?{nextCursor}:{})};}
 public async listForAnalytics(filters:OccurrenceFilterOptions,max:number):Promise<{items:StoredOccurrence[];truncated:boolean;total:number}>{const f:OccurrenceFilterOptions={...filters,cursor:undefined,pageSize:100};let q:Query<DocumentData>=applyFilters(this.collection,f,new Date());const total=(await q.count().get()).data().count;for(const [field,dir] of ordering('oldest',f))q=q.orderBy(field==='__name__'?FieldPath.documentId():field,dir);const s=await q.limit(max+1).get();return{items:s.docs.slice(0,max).map(snapshotToOccurrence),truncated:s.size>max,total};}
 public async listForExport(filters:OccurrenceFilterOptions,max:number):Promise<{items:StoredOccurrence[];truncated:boolean}>{let q:Query<DocumentData>=applyFilters(this.collection,{...filters,cursor:undefined},new Date());for(const [field,dir] of ordering(filters.sort,filters))q=q.orderBy(field==='__name__'?FieldPath.documentId():field,dir);const s=await q.limit(max+1).get();return{items:s.docs.slice(0,max).map(snapshotToOccurrence),truncated:s.size>max};}
 public async countFiltered(filters:OccurrenceFilterOptions):Promise<number>{const q=applyFilters(this.collection,{...filters,cursor:undefined},new Date());return(await q.count().get()).data().count;}
 public async listAttachmentGroup(occurrenceId:string):Promise<StoredOccurrence[]>{const current=await this.getById(occurrenceId);if(!current)return[];const rootId=current.attachedToOccurrenceId??current.id;const [root,children]=await Promise.all([this.getById(rootId),this.collection.where('attachedToOccurrenceId','==',rootId).get()]);const items:StoredOccurrence[]=[];if(root)items.push(root);for(const doc of children.docs){if(!items.some(item=>item.id===doc.id))items.push(snapshotToOccurrence(doc));}return items;}
 public async updateWithEvents(next:StoredOccurrence,expectedVersion:number,events:NewOccurrenceEvent[],photoMutations:OccurrencePhotoMutations={},notificationItems:NotificationOutboxItem[]=[],propagation?:OccurrenceOperationalPropagation):Promise<StoredOccurrence>{
  const ref=this.collection.doc(next.id);
  await this.firestore.runTransaction(async tx=>{
   const s=await tx.get(ref);if(!s.exists)throw new Error('OCCURRENCE_NOT_FOUND');
   const current=snapshotToOccurrence(s);if(current.version!==expectedVersion)throw new OccurrenceVersionConflictError();
   if(next.duplicateOfOccurrenceId){const visited=new Set<string>();let id:string|undefined=next.duplicateOfOccurrenceId;for(let depth=0;depth<100&&id;depth+=1){if(id===next.id||visited.has(id))throw new DuplicateCycleError();visited.add(id);const targetRef=this.collection.doc(id);const target:DocumentSnapshot<DocumentData>=await tx.get(targetRef);if(!target.exists)throw new DuplicateTargetNotFoundError();id=snapshotToOccurrence(target).duplicateOfOccurrenceId;}if(id)throw new DuplicateCycleError();}
   const propagationMembers:Array<{ref:DocumentSnapshot<DocumentData>['ref'];occurrence:StoredOccurrence}>=[];
   if(propagation?.enabled){
    const rootId=current.attachedToOccurrenceId??current.id;
    const rootSnapshot=rootId===current.id?s:await tx.get(this.collection.doc(rootId));
    if(!rootSnapshot.exists)throw new Error('ATTACHMENT_ROOT_NOT_FOUND');
    const children=await tx.get(this.collection.where('attachedToOccurrenceId','==',rootId));
    const memberSnapshots=[rootSnapshot,...children.docs];const unique=new Set<string>();
    for(const memberSnapshot of memberSnapshots){if(unique.has(memberSnapshot.id)||memberSnapshot.id===current.id)continue;unique.add(memberSnapshot.id);propagationMembers.push({ref:memberSnapshot.ref,occurrence:snapshotToOccurrence(memberSnapshot)});}
    if(propagationMembers.length>99)throw new AttachmentGroupTooLargeError();
   }
   tx.set(ref,occurrenceToFirestore(next));for(const e of events)tx.create(ref.collection('events').doc(),eventToFirestore(e));
   for(const member of propagationMembers){const synced=synchronizeOperationalState(member.occurrence,next);tx.set(member.ref,occurrenceToFirestore(synced));for(const e of propagation?.events??[])tx.create(member.ref.collection('events').doc(),eventToFirestore(e));}
   for(const p of photoMutations.create??[])tx.create(ref.collection('photos').doc(p.id),photoMetadataToFirestore(p));for(const p of photoMutations.update??[])tx.set(ref.collection('photos').doc(p.id),photoMetadataToFirestore(p));for(const n of notificationItems)tx.create(this.firestore.collection('notificationOutbox').doc(n.id),notificationToFirestore(n));
  });return structuredClone(next);
 }
 public async wouldCreateDuplicateCycle(sourceId:string,targetId:string):Promise<boolean>{if(sourceId===targetId)return true;const visited=new Set<string>();let id:string|undefined=targetId;for(let d=0;d<100&&id;d+=1){if(id===sourceId||visited.has(id))return true;visited.add(id);id=(await this.getById(id))?.duplicateOfOccurrenceId;}return id!==undefined;}
 public async isLocationReferenced(buildingId:string,roomId?:string):Promise<boolean>{if(roomId){const s1=await this.collection.where('location.roomId','==',roomId).limit(1).get();if(!s1.empty)return true;const s2=await this.collection.where('reportedLocation.roomId','==',roomId).limit(1).get();return!s2.empty;}const s1=await this.collection.where('location.buildingId','==',buildingId).limit(1).get();if(!s1.empty)return true;const s2=await this.collection.where('reportedLocation.buildingId','==',buildingId).limit(1).get();return!s2.empty;}
 public async count(f:OccurrenceCountFilter):Promise<number>{let q:Query<DocumentData>=this.collection;if(f.assignedToAdminUserId)q=q.where('assignedToAdminUserId','==',f.assignedToAdminUserId);if(f.assignedTeamId)q=q.where('assignedTeamId','==',f.assignedTeamId);if(f.status)q=q.where('status','==',f.status);if(f.statuses?.length)q=q.where('status','in',f.statuses);if(f.priorities?.length)q=q.where('priority','in',f.priorities);if(f.createdAtFrom)q=q.where('createdAt','>=',ts(f.createdAtFrom));if(f.createdAtTo)q=q.where('createdAt','<=',ts(f.createdAtTo));if(f.resolvedAtFrom)q=q.where('resolvedAt','>=',ts(f.resolvedAtFrom));if(f.resolvedAtTo)q=q.where('resolvedAt','<=',ts(f.resolvedAtTo));if(f.closedAtFrom)q=q.where('closedAt','>=',ts(f.closedAtFrom));if(f.closedAtTo)q=q.where('closedAt','<=',ts(f.closedAtTo));if(f.isClosed!==undefined)q=q.where('isClosed','==',f.isClosed);if(f.hasTeam!==undefined)q=q.where('hasTeam','==',f.hasTeam);if(f.hasResponsible!==undefined)q=q.where('hasResponsible','==',f.hasResponsible);if(f.dataClassification)q=q.where('dataClassification','==',f.dataClassification);if(f.slaBreachedAt)q=q.where('isClosed','==',false).where('sla.resolutionPaused','==',false).where('sla.resolutionDueAt','<',ts(f.slaBreachedAt));return(await q.count().get()).data().count;}
 public async deleteOccurrenceTree(id:string):Promise<void>{const ref=this.collection.doc(id);for(const sub of ['events','photos']){const s=await ref.collection(sub).get();for(let i=0;i<s.docs.length;i+=400){const batch=this.firestore.batch();for(const d of s.docs.slice(i,i+400))batch.delete(d.ref);await batch.commit();}}await ref.delete();}
}
