import type { DocumentData, DocumentSnapshot, Firestore, QueryDocumentSnapshot } from 'firebase-admin/firestore';
import { Timestamp } from 'firebase-admin/firestore';
import type { AdminRole } from '../../src/models/admin';
import type { InternalNoteAudience, OccurrenceEventType, OccurrenceEventVisibility } from '../../src/models/occurrence';
import type { NewOccurrenceEvent, OccurrenceEventRecord } from '../models/occurrenceDomain';
const EVENT_READ_LIMIT=1000;
function optionalString(v:unknown):string|undefined{return typeof v==='string'&&v.trim()!==''?v:undefined;}
function toDate(v:unknown):Date{if(v instanceof Timestamp)return v.toDate();if(v instanceof Date)return v;throw new Error('Timestamp de evento inválido no Firestore.');}
export function eventToFirestore(event:NewOccurrenceEvent):DocumentData{return{schemaVersion:2,eventType:event.eventType,visibility:event.visibility,...(event.audience===undefined?{}:{audience:event.audience}),...(event.audienceTeamIdSnapshot===undefined?{}:{audienceTeamIdSnapshot:event.audienceTeamIdSnapshot}),createdAt:Timestamp.fromDate(event.createdAt),actorType:event.actorType,...(event.actorAdminUserId===undefined?{}:{actorAdminUserId:event.actorAdminUserId}),...(event.actorUid===undefined?{}:{actorUid:event.actorUid}),...(event.actorRoleSnapshot===undefined?{}:{actorRoleSnapshot:event.actorRoleSnapshot}),...(event.actorDisplayNameSnapshot===undefined?{}:{actorDisplayNameSnapshot:event.actorDisplayNameSnapshot}),...(event.publicDescription===undefined?{}:{publicDescription:event.publicDescription}),...(event.internalDescription===undefined?{}:{internalDescription:event.internalDescription}),...(event.previousValue===undefined?{}:{previousValue:event.previousValue}),...(event.newValue===undefined?{}:{newValue:event.newValue}),...(event.reason===undefined?{}:{reason:event.reason}),correlationId:event.correlationId};}
function snapshotToEvent(s:DocumentSnapshot|QueryDocumentSnapshot):OccurrenceEventRecord{const d=s.data()??{};return{id:s.id,schemaVersion:2,eventType:d.eventType as OccurrenceEventType,visibility:d.visibility as OccurrenceEventVisibility,...(typeof d.audience==='string'?{audience:d.audience as InternalNoteAudience}:{}),...(optionalString(d.audienceTeamIdSnapshot)?{audienceTeamIdSnapshot:optionalString(d.audienceTeamIdSnapshot)}:{}),createdAt:toDate(d.createdAt),actorType:d.actorType==='ADMIN'?'ADMIN':'SYSTEM',...(optionalString(d.actorAdminUserId)?{actorAdminUserId:optionalString(d.actorAdminUserId)}:{}),...(optionalString(d.actorUid)?{actorUid:optionalString(d.actorUid)}:{}),...(optionalString(d.actorRoleSnapshot)?{actorRoleSnapshot:optionalString(d.actorRoleSnapshot) as AdminRole|'Sistema'}:{}),...(optionalString(d.actorDisplayNameSnapshot)?{actorDisplayNameSnapshot:optionalString(d.actorDisplayNameSnapshot)}:{}),...(optionalString(d.publicDescription)?{publicDescription:optionalString(d.publicDescription)}:{}),...(optionalString(d.internalDescription)?{internalDescription:optionalString(d.internalDescription)}:{}),...(optionalString(d.previousValue)?{previousValue:optionalString(d.previousValue)}:{}),...(optionalString(d.newValue)?{newValue:optionalString(d.newValue)}:{}),...(optionalString(d.reason)?{reason:optionalString(d.reason)}:{}),correlationId:String(d.correlationId??'')};}
export interface OccurrenceEventRepository{listByOccurrenceId(occurrenceId:string):Promise<OccurrenceEventRecord[]>;}
export class FirestoreOccurrenceEventRepository implements OccurrenceEventRepository{public constructor(private readonly firestore:Firestore){}public async listByOccurrenceId(id:string):Promise<OccurrenceEventRecord[]>{const s=await this.firestore.collection('occurrences').doc(id).collection('events').orderBy('createdAt','asc').limit(EVENT_READ_LIMIT).get();return s.docs.map(snapshotToEvent);}}
