import type { DocumentSnapshot, Firestore } from 'firebase-admin/firestore';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import type { OperationalTeam, TeamCreateInput, TeamUpdateInput } from '../../src/models/operations';

function iso(value:unknown):string{if(value instanceof Timestamp)return value.toDate().toISOString();if(value instanceof Date)return value.toISOString();if(typeof value==='string')return value;return new Date(0).toISOString();}
function fromSnapshot(s:DocumentSnapshot):OperationalTeam{const d=s.data()??{};return{id:s.id,schemaVersion:1,name:String(d.name??''),...(typeof d.description==='string'&&d.description!==''?{description:d.description}:{}),active:d.active===true,sortOrder:Number(d.sortOrder??0),memberAdminUserIds:Array.isArray(d.memberAdminUserIds)?d.memberAdminUserIds.filter((x):x is string=>typeof x==='string'):[],createdAt:iso(d.createdAt),createdBy:String(d.createdBy??''),updatedAt:iso(d.updatedAt),updatedBy:String(d.updatedBy??'')};}
export interface OperationalTeamRepository{list(includeInactive?:boolean):Promise<OperationalTeam[]>;getById(id:string):Promise<OperationalTeam|undefined>;create(id:string,input:TeamCreateInput,actorId:string):Promise<OperationalTeam>;update(id:string,input:TeamUpdateInput,actorId:string):Promise<OperationalTeam>;}
export class FirestoreOperationalTeamRepository implements OperationalTeamRepository{
  private readonly collection;public constructor(private readonly firestore:Firestore){this.collection=firestore.collection('operationalTeams');}
  public async list(includeInactive=true):Promise<OperationalTeam[]>{const s=await this.collection.get();return s.docs.map(fromSnapshot).filter(x=>includeInactive||x.active).sort((a,b)=>a.sortOrder-b.sortOrder||a.name.localeCompare(b.name,'pt-BR'));}
  public async getById(id:string):Promise<OperationalTeam|undefined>{const s=await this.collection.doc(id).get();return s.exists?fromSnapshot(s):undefined;}
  public async create(id:string,input:TeamCreateInput,actorId:string):Promise<OperationalTeam>{const ref=this.collection.doc(id);const now=new Date().toISOString();const team:OperationalTeam={id,schemaVersion:1,name:input.name,...(input.description?{description:input.description}:{}),active:input.active??true,sortOrder:input.sortOrder,memberAdminUserIds:input.memberAdminUserIds??[],createdAt:now,createdBy:actorId,updatedAt:now,updatedBy:actorId};await this.firestore.runTransaction(async tx=>{if((await tx.get(ref)).exists)throw new Error('TEAM_EXISTS');tx.create(ref,{schemaVersion:1,name:team.name,...(team.description?{description:team.description}:{}),active:team.active,sortOrder:team.sortOrder,memberAdminUserIds:team.memberAdminUserIds,createdAt:FieldValue.serverTimestamp(),createdBy:actorId,updatedAt:FieldValue.serverTimestamp(),updatedBy:actorId});});return team;}
  public async update(id:string,input:TeamUpdateInput,actorId:string):Promise<OperationalTeam>{const ref=this.collection.doc(id);return this.firestore.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new Error('TEAM_NOT_FOUND');const before=fromSnapshot(s);const after:OperationalTeam={...before,...(input.name===undefined?{}:{name:input.name}),...(input.description===undefined?{}:{description:input.description}),...(input.active===undefined?{}:{active:input.active}),...(input.sortOrder===undefined?{}:{sortOrder:input.sortOrder}),...(input.memberAdminUserIds===undefined?{}:{memberAdminUserIds:input.memberAdminUserIds}),updatedAt:new Date().toISOString(),updatedBy:actorId};tx.update(ref,{name:after.name,description:after.description??FieldValue.delete(),active:after.active,sortOrder:after.sortOrder,memberAdminUserIds:after.memberAdminUserIds,updatedAt:FieldValue.serverTimestamp(),updatedBy:actorId});return after;});}
}
