import { APP_VERSION } from '../config/version';
import { z } from 'zod';
import { ADMIN_ROLES, AUDIT_EVENT_TYPES, LEGACY_ADMIN_ROLES, type AdminAssignee, type AdminSession, type AdminUser, type AuditLog, type AuditLogPage } from '../models/admin';
import type { BootstrapData, PublicSystemConfig, SystemConfig } from '../models/config';
import type { AnalyticsStats, OperationalTeam, ServiceCalendar, ServiceCalendarException, SlaConfiguration } from '../models/operations';
import { INTERNAL_NOTE_AUDIENCES, OCCURRENCE_PRIORITIES, OCCURRENCE_STATUSES, type CreateOccurrenceResponse, type DashboardStats, type Occurrence, type OccurrenceListResponse, type PublicOccurrence } from '../models/occurrence';

const adminRole=z.enum(ADMIN_ROLES);const storedRole=z.union([adminRole,z.enum(LEGACY_ADMIN_ROLES)]);
export const adminUserResponseSchema:z.ZodType<AdminUser>=z.object({id:z.string(),email:z.string().email(),normalizedEmail:z.string().email(),uid:z.string().optional(),displayName:z.string(),role:storedRole,department:z.string().optional(),teamIds:z.array(z.string()),active:z.boolean(),legacyRole:z.boolean(),createdAt:z.string(),createdBy:z.string(),updatedAt:z.string(),updatedBy:z.string(),lastAuthorizedLoginAt:z.string().optional()});
export const adminAssigneesResponseSchema:z.ZodType<AdminAssignee[]>=z.array(z.object({id:z.string(),email:z.string().email(),displayName:z.string(),role:adminRole,teamIds:z.array(z.string())}));
export const adminUsersResponseSchema:z.ZodType<AdminUser[]>=z.array(adminUserResponseSchema);
const authorizedAdminProfileSchema=z.object({id:z.string(),uid:z.string(),email:z.string().email(),displayName:z.string(),role:adminRole,department:z.string().optional(),teamIds:z.array(z.string()),active:z.literal(true),lastAuthorizedLoginAt:z.string().optional()});
export const adminSessionResponseSchema:z.ZodType<AdminSession>=z.object({user:authorizedAdminProfileSchema});
export const auditLogResponseSchema:z.ZodType<AuditLog>=z.object({id:z.string(),eventType:z.enum(AUDIT_EVENT_TYPES),actorUid:z.string().optional(),actorEmail:z.string().optional(),actorRole:adminRole.optional(),targetType:z.enum(['adminUser','adminSession','security','systemConfig','occurrence','category','location','team','sla','calendar','report']),targetId:z.string().optional(),timestamp:z.string(),summary:z.string(),requestCorrelationId:z.string().optional(),metadata:z.record(z.string(),z.union([z.string(),z.number(),z.boolean()])).optional()});
export const auditLogsResponseSchema:z.ZodType<AuditLog[]>=z.array(auditLogResponseSchema);
export const auditLogPageResponseSchema:z.ZodType<AuditLogPage>=z.object({items:z.array(auditLogResponseSchema),limit:z.number(),nextCursor:z.string().optional(),hasMore:z.boolean()});

const categorySchema=z.object({id:z.string(),name:z.string(),description:z.string(),active:z.boolean(),sortOrder:z.number().int(),resolutionBaseBusinessHours:z.number(),version:z.number().int()});
const roomSchema=z.object({id:z.string(),name:z.string(),active:z.boolean().optional(),sortOrder:z.number().optional()});
const floorSchema=z.object({id:z.string(),name:z.string(),rooms:z.array(roomSchema)});const buildingSchema=z.object({id:z.string(),name:z.string(),active:z.boolean().optional(),sortOrder:z.number().optional(),floors:z.array(floorSchema)});const campusSchema=z.object({id:z.string(),campusName:z.string(),buildings:z.array(buildingSchema),provisional:z.boolean().optional(),version:z.number().optional()});
export const categoriesResponseSchema=z.array(categorySchema);export const locationsResponseSchema=z.array(campusSchema);
export const systemConfigResponseSchema:z.ZodType<SystemConfig>=z.object({institutionDisplayName:z.string(),protocolPrefix:z.string(),notificationEmails:z.array(z.string()),autoAssignRisk:z.boolean(),serviceNotice:z.string()});
export const configUpdateResponseSchema:z.ZodType<{config:SystemConfig}>=z.object({config:systemConfigResponseSchema});const publicSystemConfigResponseSchema:z.ZodType<PublicSystemConfig>=z.object({institutionDisplayName:z.string(),serviceNotice:z.string()}).strict();
export const bootstrapResponseSchema:z.ZodType<BootstrapData>=z.object({config:publicSystemConfigResponseSchema,categories:z.array(categorySchema),locations:z.array(campusSchema),runtime:z.object({version:z.literal(APP_VERSION),emulatorMode:z.boolean(),firebaseIntegrated:z.literal(true),publicAuthentication:z.literal('firebase-anonymous'),adminAuthentication:z.literal('google'),adminAuthorization:z.literal('firestore'),occurrencePersistence:z.literal('firestore'),referenceDataPersistence:z.literal('firestore'),photoStorage:z.literal('firebase-storage'),photoUploadEnabled:z.literal(true),maxInitialPhotos:z.literal(3),maxResolutionPhotos:z.literal(3),emailDelivery:z.literal(false),appCheckEnforced:z.boolean()})});

const locationSchema=z.object({campusId:z.string().optional(),campusName:z.string(),buildingId:z.string().optional(),buildingName:z.string(),floorId:z.string().optional(),floor:z.string(),roomId:z.string().optional(),room:z.string(),complement:z.string().optional(),isOther:z.boolean().optional(),otherDescription:z.string().optional()});
const publicLocationSchema=z.object({campusName:z.string(),buildingName:z.string(),floor:z.string(),room:z.string(),complement:z.string().optional(),isOther:z.boolean().optional(),otherDescription:z.string().optional()}).strict();
const timelineEventSchema=z.object({id:z.string(),date:z.string(),title:z.string(),description:z.string().optional(),isPublic:z.boolean(),authorRole:z.string().optional()});const publicMessageSchema=z.object({id:z.string(),date:z.string(),message:z.string(),authorRole:z.string()});const internalNoteSchema=z.object({id:z.string(),date:z.string(),note:z.string(),authorName:z.string(),authorRole:z.string(),audience:z.enum(INTERNAL_NOTE_AUDIENCES)});
const occurrencePhotoSchema=z.object({id:z.string(),kind:z.enum(['INITIAL','RESOLUTION']),visibility:z.enum(['INTERNAL','PUBLIC']),status:z.enum(['READY','DELETED']),width:z.number().int().positive(),height:z.number().int().positive(),byteSize:z.number().int().nonnegative(),createdAt:z.string()}).strict();const publicOccurrencePhotoSchema=z.object({id:z.string(),kind:z.literal('RESOLUTION'),createdAt:z.string(),width:z.number().int().positive(),height:z.number().int().positive()}).strict();
const slaSchema=z.object({schemaVersion:z.literal(1),policyVersion:z.string(),firstResponseTargetBusinessMinutes:z.number(),firstResponseDueAt:z.string(),firstResponseAt:z.string().optional(),firstResponseOutcome:z.enum(['ON_TIME','BREACHED']).optional(),resolutionBaseBusinessMinutes:z.number(),priorityMultiplier:z.number(),resolutionTargetBusinessMinutes:z.number(),resolutionDueAt:z.string(),resolutionNearDueAt:z.string(),resolutionPaused:z.boolean(),resolutionPauseStartedAt:z.string().optional(),accumulatedPausedBusinessMinutes:z.number(),effectiveElapsedBusinessMinutes:z.number(),completedAt:z.string().optional(),resolutionOutcome:z.enum(['ON_TIME','BREACHED']).optional(),calendarSnapshotId:z.string(),legacyAssessment:z.enum(['CALCULATED','ESTIMATED','UNAVAILABLE']).optional()});
export const occurrenceResponseSchema:z.ZodType<Occurrence>=z.object({id:z.string(),protocol:z.string(),reportedLocation:locationSchema,location:locationSchema,reportedCategoryId:z.string(),reportedCategoryName:z.string(),categoryId:z.string(),categoryName:z.string(),description:z.string(),immediateRisk:z.boolean(),status:z.enum(OCCURRENCE_STATUSES),priority:z.enum(OCCURRENCE_PRIORITIES),assignedTeamId:z.string().optional(),assignedTeamNameSnapshot:z.string().optional(),assignedToAdminUserId:z.string().optional(),assignedToDisplayNameSnapshot:z.string().optional(),createdAt:z.string(),updatedAt:z.string(),closedAt:z.string().optional(),resolvedAt:z.string().optional(),firstPublicResponseAt:z.string().optional(),duplicateOfProtocol:z.string().optional(),version:z.number().int().min(1),dataClassification:z.enum(['REAL','TEST']),reopenedCount:z.number().int().nonnegative(),sla:slaSchema.optional(),slaStatus:z.enum(['ON_TIME','NEAR_DUE','BREACHED','PAUSED','COMPLETED']).optional(),totalOpenHours:z.number().nonnegative(),effectiveBusinessHours:z.number().nonnegative(),timeline:z.array(timelineEventSchema),publicMessages:z.array(publicMessageSchema),internalNotes:z.array(internalNoteSchema),photos:z.array(occurrencePhotoSchema)});
export const publicOccurrenceResponseSchema:z.ZodType<PublicOccurrence>=z.object({protocol:z.string(),category:z.string(),location:publicLocationSchema,description:z.string(),immediateRisk:z.boolean(),status:z.enum(OCCURRENCE_STATUSES),createdAt:z.string(),updatedAt:z.string(),closedAt:z.string().optional(),resolvedAt:z.string().optional(),duplicateOfProtocol:z.string().optional(),categoryAdjusted:z.boolean(),locationAdjusted:z.boolean(),timeline:z.array(timelineEventSchema),publicMessages:z.array(publicMessageSchema),photos:z.array(publicOccurrencePhotoSchema)}).strict();
export const occurrenceListResponseSchema:z.ZodType<OccurrenceListResponse>=z.object({items:z.array(occurrenceResponseSchema),limit:z.number().int().positive(),loadedCount:z.number().int().nonnegative(),hasMore:z.boolean(),nextCursor:z.string().optional()});
export const createOccurrenceResponseSchema:z.ZodType<CreateOccurrenceResponse>=z.object({protocol:z.string(),trackingKey:z.string(),createdAt:z.string()});
export const dashboardStatsResponseSchema:z.ZodType<DashboardStats>=z.object({urgentOrEmergency:z.number().int().nonnegative(),slaBreached:z.number().int().nonnegative(),withoutRouting:z.number().int().nonnegative(),inService:z.number().int().nonnegative(),awaitingAction:z.number().int().nonnegative(),resolvedRecently:z.number().int().nonnegative(),receivedToday:z.number().int().nonnegative()});

const teamSchema:z.ZodType<OperationalTeam>=z.object({id:z.string(),schemaVersion:z.literal(1),name:z.string(),description:z.string().optional(),active:z.boolean(),sortOrder:z.number(),memberAdminUserIds:z.array(z.string()),createdAt:z.string(),createdBy:z.string(),updatedAt:z.string(),updatedBy:z.string()});export const teamsResponseSchema=z.array(teamSchema);
const day=z.object({open:z.boolean(),start:z.string(),end:z.string()});export const calendarResponseSchema:z.ZodType<ServiceCalendar>=z.object({id:z.literal('default'),schemaVersion:z.literal(1),timezone:z.literal('America/Sao_Paulo'),weekly:z.object({MONDAY:day,TUESDAY:day,WEDNESDAY:day,THURSDAY:day,FRIDAY:day,SATURDAY:day,SUNDAY:day}),version:z.number(),updatedAt:z.string(),updatedBy:z.string()});
export const exceptionResponseSchema:z.ZodType<ServiceCalendarException>=z.object({id:z.string(),schemaVersion:z.literal(1),date:z.string(),type:z.enum(['FERIADO','RECESSO','SUSPENSAO','HORARIO_ESPECIAL']),label:z.string(),closed:z.boolean(),start:z.string().optional(),end:z.string().optional(),createdAt:z.string(),createdBy:z.string(),updatedAt:z.string(),updatedBy:z.string()});
const priorityRecord=z.object({Baixa:z.number(),Normal:z.number(),Alta:z.number(),Urgente:z.number(),Emergencial:z.number()});export const slaConfigurationSchema:z.ZodType<SlaConfiguration>=z.object({schemaVersion:z.literal(1),policyVersion:z.string(),firstResponseBusinessHours:priorityRecord,priorityMultipliers:priorityRecord,nearDueThresholdPercent:z.number(),version:z.number(),updatedAt:z.string(),updatedBy:z.string()});export const slaSettingsResponseSchema=z.object({config:slaConfigurationSchema,calendar:calendarResponseSchema,exceptions:z.array(exceptionResponseSchema)});
const named=z.object({name:z.string(),value:z.number()});export const analyticsResponseSchema:z.ZodType<AnalyticsStats>=z.object({period:z.object({start:z.string(),end:z.string()}),openNow:z.number(),createdInPeriod:z.number(),urgentOrEmergency:z.number(),slaBreached:z.number(),withoutTeam:z.number(),withoutResponsible:z.number(),resolvedInPeriod:z.number(),closedInPeriod:z.number(),reopenedInPeriod:z.number(),averageFirstResponseBusinessHours:z.number().nullable(),medianFirstResponseBusinessHours:z.number().nullable(),averageTotalClosureHours:z.number().nullable(),medianTotalClosureHours:z.number().nullable(),averageEffectiveBusinessHours:z.number().nullable(),medianEffectiveBusinessHours:z.number().nullable(),firstResponseOnTimePercent:z.number().nullable(),resolutionOnTimePercent:z.number().nullable(),byCategory:z.array(named),byStatus:z.array(named),byPriority:z.array(named),byArea:z.array(named),byTeam:z.array(named),byResponsible:z.array(named),unavailableMetrics:z.array(z.string())});
