import type { AdminAssignee, AdminUser, AdminUserCreateInput, AdminUserUpdateInput, AuditLog, AuthorizedAdminProfile, LegacyAdminResolutionInput } from '../../src/models/admin';
import { isAdminRole } from '../../src/models/admin';
import { AdminUserConflictError, AdminUserNotFoundError, LastAdministratorProtectedError } from '../repositories/adminUserRepository';
import type { AdminUserRepository } from '../repositories/adminUserRepository';
import type { AuditLogRepository } from '../repositories/auditLogRepository';
import { HttpError } from '../types/errors';
import { emailDomain, validateEmail } from '../utils/email';

export class AdminUserService{
 private readonly allowedDomains:Set<string>;public constructor(private readonly users:AdminUserRepository,private readonly auditLogs:AuditLogRepository,allowedDomains:readonly string[]){this.allowedDomains=new Set(allowedDomains.map(x=>x.toLowerCase()));}
 private assertSystemAdmin(actor:AuthorizedAdminProfile):void{if(actor.role!=='Administrador')throw new HttpError(403,'FORBIDDEN','Esta operação é exclusiva de Administradores.');}
 public list(limit=100):Promise<AdminUser[]>{return this.users.list(Math.min(Math.max(limit,1),200));}
 public async listAssignees():Promise<AdminAssignee[]>{const users=await this.users.list(200);return users.filter((u):u is AdminUser & {role:'Administrador'|'Gestor'}=>u.active&&isAdminRole(u.role)).map(u=>({id:u.id,email:u.email,displayName:u.displayName,role:u.role,teamIds:u.teamIds}));}
 public listAuditLogs(limit=100):Promise<AuditLog[]>{return this.auditLogs.list(Math.min(Math.max(limit,1),200));}
 public async create(input:AdminUserCreateInput,actor:AuthorizedAdminProfile,correlationId:string):Promise<AdminUser>{this.assertSystemAdmin(actor);const normalizedEmail=this.validateAllowedEmail(input.email);try{const created=await this.users.create({...input,normalizedEmail,actorId:actor.id});await this.auditLogs.write({eventType:'ADMIN_USER_CREATED',actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,targetType:'adminUser',targetId:created.id,summary:`Autorização administrativa criada com papel ${created.role}.`,requestCorrelationId:correlationId});return created;}catch(error){if(error instanceof AdminUserConflictError)throw new HttpError(409,'CONFLICT',error.message);throw error;}}
 public async update(id:string,input:AdminUserUpdateInput,actor:AuthorizedAdminProfile,correlationId:string):Promise<AdminUser>{this.assertSystemAdmin(actor);try{const{before,after}=await this.users.update(id,input,actor.id);const base={actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,targetType:'adminUser' as const,targetId:id,requestCorrelationId:correlationId};if(before.role!==after.role)await this.auditLogs.write({...base,eventType:'ADMIN_ROLE_CHANGED',summary:`Papel administrativo alterado de ${before.role} para ${after.role}.`});if(before.active!==after.active)await this.auditLogs.write({...base,eventType:after.active?'ADMIN_USER_ACTIVATED':'ADMIN_USER_DEACTIVATED',summary:after.active?'Cadastro administrativo ativado.':'Cadastro administrativo inativado.'});if(before.role===after.role&&before.active===after.active)await this.auditLogs.write({...base,eventType:'ADMIN_USER_UPDATED',summary:'Dados institucionais do cadastro administrativo atualizados.'});return after;}catch(error){if(error instanceof AdminUserNotFoundError)throw new HttpError(404,'NOT_FOUND',error.message);if(error instanceof LastAdministratorProtectedError){await this.auditLogs.write({eventType:'LAST_ADMIN_CHANGE_BLOCKED',actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,targetType:'adminUser',targetId:id,summary:'Alteração bloqueada para preservar ao menos um Administrador ativo.',requestCorrelationId:correlationId});throw new HttpError(409,'CONFLICT',error.message);}if(error instanceof AdminUserConflictError)throw new HttpError(409,'CONFLICT',error.message);throw error;}}
 public async resolveLegacy(id:string,input:LegacyAdminResolutionInput,actor:AuthorizedAdminProfile,correlationId:string):Promise<AdminUser>{this.assertSystemAdmin(actor);try{const updated=await this.users.resolveLegacy(id,input.action,actor.id);await this.auditLogs.write({eventType:'LEGACY_ADMIN_ROLE_RESOLVED',actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,targetType:'adminUser',targetId:id,summary:input.action==='CONVERT_TO_MANAGER'?'Papel legado Atendente convertido explicitamente para Gestor.':'Usuário com papel legado Atendente inativado.',requestCorrelationId:correlationId});return updated;}catch(error){if(error instanceof AdminUserNotFoundError)throw new HttpError(404,'NOT_FOUND','Usuário administrativo não encontrado.');if(error instanceof AdminUserConflictError)throw new HttpError(409,'CONFLICT',error.message);throw error;}}
 private validateAllowedEmail(email:string):string{let normalized:string;try{normalized=validateEmail(email);}catch(error){throw new HttpError(400,'VALIDATION_ERROR',error instanceof Error?error.message:'E-mail inválido.');}if(!this.allowedDomains.has(emailDomain(normalized)))throw new HttpError(403,'DOMAIN_NOT_ALLOWED','O e-mail informado não pertence a um domínio administrativo autorizado.');return normalized;}
}
