import type { AuthorizedAdminProfile } from '../../src/models/admin';
import type {
  CapacityLevel,
  InfrastructureCapacitySettings,
  InfrastructureOverview,
  InfrastructureProjection,
  InfrastructureSnapshot,
  StorageReconciliationReport,
} from '../../src/models/infrastructure';
import type { AuditLogRepository } from '../repositories/auditLogRepository';
import type { FirestoreLogicalEstimate, InfrastructureRepository } from '../repositories/infrastructureRepository';
import type { NotificationOutboxRepository } from '../repositories/notificationOutboxRepository';
import type { PhotoMetadataRepository } from '../repositories/photoMetadataRepository';
import type { PhotoObjectInfo, PhotoRepository } from '../repositories/photoRepository';
import type { StorageCleanupTaskRepository } from '../repositories/storageCleanupTaskRepository';
import { HttpError } from '../types/errors';
import type { NotificationService } from './notificationService';

const MAX_INVENTORY_OBJECTS = 50_000;

function ratio(value: number | null, reference: number): number | null { return value === null || reference <= 0 ? null : (value / reference) * 100; }
export function capacityLevel(percent: number | null, settings:InfrastructureCapacitySettings):CapacityLevel{if(percent===null)return'Não medido';if(percent>=settings.criticalPercent)return'Crítico';if(percent>=settings.alertPercent)return'Alerta';if(percent>=settings.warningPercent)return'Atenção';return'Normal';}

export function capacityProjection(metric:InfrastructureProjection['metric'],current:number|null,reference:number,history:InfrastructureSnapshot[],select:(snapshot:InfrastructureSnapshot)=>number|null):InfrastructureProjection{
  if(current===null||history.length<2)return{metric,monthlyGrowthBytes:null,monthsToReference:null,message:'Ainda não há histórico suficiente para projeção.'};
  const newest=history[0];const oldest=history.at(-1);if(newest===undefined||oldest===undefined)return{metric,monthlyGrowthBytes:null,monthsToReference:null,message:'Ainda não há histórico suficiente para projeção.'};
  const newestValue=select(newest),oldestValue=select(oldest);const days=(new Date(newest.capturedAt).getTime()-new Date(oldest.capturedAt).getTime())/86_400_000;
  if(newestValue===null||oldestValue===null||days<7)return{metric,monthlyGrowthBytes:null,monthsToReference:null,message:'Ainda não há histórico suficiente para projeção.'};
  const monthly=((newestValue-oldestValue)/days)*30;if(monthly<=0)return{metric,monthlyGrowthBytes:monthly,monthsToReference:null,message:'O histórico observado não apresenta crescimento positivo suficiente para projeção.'};
  const months=Math.max(0,(reference-current)/monthly);return{metric,monthlyGrowthBytes:monthly,monthsToReference:months,message:`Mantido o ritmo observado nos últimos ${Math.round(days)} dias, a referência operacional seria atingida aproximadamente em ${months.toFixed(1)} meses.`};
}

function notificationSnapshot(metrics:Awaited<ReturnType<NotificationOutboxRepository['metrics']>>):InfrastructureSnapshot['notifications']{return{...metrics,oldestPendingAt:metrics.oldestPendingAt?.toISOString()??null,oldestUnmatchedWebhookAt:metrics.oldestUnmatchedWebhookAt?.toISOString()??null,lastAttemptAt:metrics.lastAttemptAt?.toISOString()??null,lastSuccessfulSendAt:metrics.lastSuccessfulSendAt?.toISOString()??null,lastError:metrics.lastError??null,lastFailureCategory:metrics.lastFailureCategory??null};}

export class InfrastructureService {
  public constructor(
    private readonly infrastructure: InfrastructureRepository,
    private readonly objects: PhotoRepository,
    private readonly photoMetadata: PhotoMetadataRepository,
    private readonly cleanupTasks: StorageCleanupTaskRepository,
    private readonly outbox: NotificationOutboxRepository,
    private readonly notifications: NotificationService,
    private readonly audit: AuditLogRepository,
    private readonly legacyObjects?: PhotoRepository,
  ) {}

  private async inventoryObjects():Promise<{items:PhotoObjectInfo[];complete:boolean}>{const items:PhotoObjectInfo[]=[];let cursor:string|undefined;do{const page=await this.objects.listPage('occurrences/',cursor,500);items.push(...page.items);cursor=page.nextCursor;if(items.length>=MAX_INVENTORY_OBJECTS&&cursor!==undefined)return{items:items.slice(0,MAX_INVENTORY_OBJECTS),complete:false};}while(cursor!==undefined);return{items,complete:true};}

  public async captureSnapshot(source:InfrastructureSnapshot['captureSource'],estimate?:FirestoreLogicalEstimate):Promise<InfrastructureSnapshot>{const now=new Date();const [inventory,counts,notificationMetrics,tasks,artifact,reconciliation,previous]=await Promise.all([this.inventoryObjects(),this.infrastructure.collectionCounts(),this.outbox.metrics(now),this.cleanupTasks.listRecent(500),this.infrastructure.latestArtifactObservation(),this.infrastructure.latestReconciliationObservation(),this.infrastructure.latest()]);const bytes=inventory.items.reduce((sum,item)=>sum+(item.size??0),0);const dated=inventory.items.flatMap(item=>item.lastModified===undefined?[]:[item.lastModified.getTime()]);const period=now.toISOString().slice(0,10);const pending=tasks.filter(task=>task.status==='PENDING');const logical=estimate??previous?.firestore??{estimatedLogicalBytes:null,estimationMethod:'Contagens agregadas; armazenamento lógico não medido nesta captura.',documentsSampled:0,coveragePercent:null};const snapshot:InfrastructureSnapshot={id:`daily-${period}`,schemaVersion:1,capturedAt:now.toISOString(),captureSource:source,period,r2:{measured:true,inventoryComplete:inventory.complete,objectCount:inventory.items.length,bytes,mainPhotoCount:inventory.items.filter(item=>!item.path.includes('-thumbnails/')).length,thumbnailCount:inventory.items.filter(item=>item.path.includes('-thumbnails/')).length,oldestObjectAt:dated.length===0?null:new Date(Math.min(...dated)).toISOString(),lastInventoryAt:now.toISOString()},firestore:{counts,totalDocuments:Object.values(counts).reduce((sum,value)=>sum+value,0),estimatedLogicalBytes:logical.estimatedLogicalBytes,estimationMethod:logical.estimationMethod,documentsSampled:logical.documentsSampled,coveragePercent:logical.coveragePercent},notifications:notificationSnapshot(notificationMetrics),cleanup:{pendingTasks:pending.length,completedTasks:tasks.filter(task=>task.status==='COMPLETED').length,pendingObjects:pending.reduce((sum,task)=>sum+task.storagePaths.length,0),oldestPendingAt:pending.length===0?null:new Date(Math.min(...pending.map(task=>task.createdAt.getTime()))).toISOString(),lastError:pending.find(task=>task.lastError!==undefined)?.lastError??null},artifactRegistry:artifact===undefined?{collected:false,capturedAt:null,bytes:null,versionCount:null,repository:null}:{collected:true,capturedAt:artifact.capturedAt,bytes:artifact.bytes,versionCount:artifact.versionCount,repository:artifact.repository},reconciliation:reconciliation===undefined?{missingObjects:0,orphanObjects:0,sizeMismatches:0,lastRunAt:null}:reconciliation};await this.infrastructure.saveSnapshot(snapshot);await this.infrastructure.cleanupTechnicalSnapshots(now);return snapshot;}

  public async overview():Promise<InfrastructureOverview>{
    const[settings,latest,history,runtime]=await Promise.all([this.infrastructure.getSettings(),this.infrastructure.latest(),this.infrastructure.history(365),this.notifications.runtimeStatus()]);
    const r2Complete=latest?.r2.inventoryComplete===true;
    const r2Observed=latest?.r2.bytes??null;
    const percentages={r2:r2Complete?ratio(r2Observed,settings.r2StorageReferenceBytes):null,firestore:ratio(latest?.firestore.estimatedLogicalBytes??null,settings.firestoreStorageReferenceBytes),artifactRegistry:ratio(latest?.artifactRegistry.bytes??null,settings.artifactRegistryStorageReferenceBytes),resendDaily:ratio(latest?.notifications.acceptedToday??0,settings.resendDailyReference),resendMonthly:ratio(latest?.notifications.acceptedThisMonth??0,settings.resendMonthlyReference)};
    const completeR2History=history.filter(snapshot=>snapshot.r2.inventoryComplete);
    const r2Projection=r2Complete
      ?capacityProjection('R2',r2Observed,settings.r2StorageReferenceBytes,completeR2History,s=>s.r2.bytes)
      :{metric:'R2' as const,monthlyGrowthBytes:null,monthsToReference:null,message:'Projeção integral indisponível: o inventário R2 mais recente é parcial.'};
    const r2Level:CapacityLevel=!r2Complete
      ?(r2Observed!==null&&r2Observed>=settings.r2StorageReferenceBytes?'Crítico':'Inventário incompleto')
      :capacityLevel(percentages.r2,settings);
    return{settings,latest,history,projections:[r2Projection,capacityProjection('Firestore',latest?.firestore.estimatedLogicalBytes??null,settings.firestoreStorageReferenceBytes,history,s=>s.firestore.estimatedLogicalBytes),capacityProjection('Artifact Registry',latest?.artifactRegistry.bytes??null,settings.artifactRegistryStorageReferenceBytes,history,s=>s.artifactRegistry.bytes)],notificationRuntime:{provider:runtime.provider,environmentEnabled:runtime.environmentEnabled,applicationEnabled:runtime.applicationEnabled,effectiveEnabled:runtime.effectiveEnabled,from:runtime.from,recipientCount:runtime.recipientCount,configurationIssues:runtime.configurationIssues},levels:{r2:{percent:percentages.r2,level:r2Level},firestore:{percent:percentages.firestore,level:capacityLevel(percentages.firestore,settings)},artifactRegistry:{percent:percentages.artifactRegistry,level:capacityLevel(percentages.artifactRegistry,settings)},resendDaily:{percent:percentages.resendDaily,level:capacityLevel(percentages.resendDaily,settings)},resendMonthly:{percent:percentages.resendMonthly,level:capacityLevel(percentages.resendMonthly,settings)}}};
  }

  public async updateSettings(input:Omit<InfrastructureCapacitySettings,'schemaVersion'|'version'|'updatedAt'|'updatedBy'>,expectedVersion:number,actor:AuthorizedAdminProfile,correlationId:string):Promise<InfrastructureCapacitySettings>{let settings:InfrastructureCapacitySettings;try{settings=await this.infrastructure.updateSettings(input,expectedVersion,actor.id);}catch(error:unknown){if(error instanceof Error&&error.message==='INFRASTRUCTURE_SETTINGS_CONFLICT')throw new HttpError(409,'CONFLICT','As referências foram atualizadas por outro Administrador. Recarregue a página.');throw error;}await this.audit.write({eventType:'INFRASTRUCTURE_SETTINGS_CHANGED',actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,targetType:'infrastructure',targetId:'capacity-settings',summary:'Referências operacionais de infraestrutura atualizadas.',requestCorrelationId:correlationId});return settings;}
  public async requestSnapshot(actor:AuthorizedAdminProfile,correlationId:string):Promise<InfrastructureSnapshot>{const snapshot=await this.captureSnapshot('ADMIN');await this.audit.write({eventType:'INFRASTRUCTURE_SNAPSHOT_REQUESTED',actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,targetType:'infrastructure',targetId:snapshot.id,summary:'Snapshot agregado de infraestrutura solicitado.',requestCorrelationId:correlationId});return snapshot;}
  public async requestFirestoreEstimate(limit:number,actor:AuthorizedAdminProfile,correlationId:string):Promise<InfrastructureSnapshot>{const estimate=await this.infrastructure.estimateFirestoreLogicalBytes(limit);const snapshot=await this.captureSnapshot('ADMIN',estimate);await this.audit.write({eventType:'FIRESTORE_ESTIMATE_REQUESTED',actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,targetType:'infrastructure',targetId:snapshot.id,summary:'Estimativa lógica paginada do Firestore solicitada.',requestCorrelationId:correlationId,metadata:{documentsSampled:estimate.documentsSampled,coveragePercent:estimate.coveragePercent??'not-available'}});return snapshot;}
  public async processCleanup(limit:number,actor?:AuthorizedAdminProfile,correlationId?:string):Promise<{processed:number;failed:number}>{const tasks=await this.cleanupTasks.listPending(Math.min(Math.max(limit,1),100));let failed=0;for(const task of tasks){try{const repository=task.storageProvider==='firebase-storage'?this.legacyObjects:this.objects;if(repository===undefined)throw new Error('LEGACY_STORAGE_UNAVAILABLE');for(const path of task.storagePaths)await repository.delete(path);await this.cleanupTasks.markCompleted(task.id);}catch(error:unknown){failed+=1;await this.cleanupTasks.markFailed(task.id,error instanceof Error?error.name:'StorageError');}}if(actor!==undefined)await this.audit.write({eventType:'STORAGE_CLEANUP_REQUESTED',actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,targetType:'storage',summary:`Processamento solicitado para ${tasks.length} tarefa(s) de limpeza.`,requestCorrelationId:correlationId,metadata:{processed:tasks.length-failed,failed}});return{processed:tasks.length-failed,failed};}
  public async reconcile(apply=false,safetyDays=7):Promise<StorageReconciliationReport>{const metadata=new Map<string,number>();let metadataCursor:string|undefined;let metadataComplete=true;let metadataCount=0;do{const page=await this.photoMetadata.listInventoryPage(metadataCursor,500);for(const item of page.items){if(item.photo.status!=='READY')continue;metadata.set(item.photo.storagePath,item.photo.byteSize);metadata.set(item.photo.thumbnailStoragePath,item.photo.thumbnailByteSize);metadataCount+=1;}metadataCursor=page.nextCursor;if(metadata.size>=MAX_INVENTORY_OBJECTS&&metadataCursor!==undefined){metadataComplete=false;break;}}while(metadataCursor!==undefined);const inventory=await this.inventoryObjects();const objects=new Map(inventory.items.map(item=>[item.path,item]));const missing=[...metadata.keys()].filter(path=>!objects.has(path));const orphans=[...objects.keys()].filter(path=>!metadata.has(path));const mismatches=[...metadata.entries()].filter(([path,size])=>objects.get(path)?.size!==undefined&&objects.get(path)?.size!==size).map(([path])=>path);const complete=metadataComplete&&inventory.complete;let deleted=0;if(apply){if(!complete)throw new Error('STORAGE_RECONCILIATION_INCOMPLETE');const cutoff=Date.now()-Math.max(safetyDays,1)*86_400_000;for(const path of orphans){const object=objects.get(path);if(object?.lastModified!==undefined&&object.lastModified.getTime()<cutoff){await this.objects.delete(path);deleted+=1;}}}const generatedAt=new Date().toISOString();await this.infrastructure.saveReconciliationObservation({missingObjects:missing.length,orphanObjects:orphans.length,sizeMismatches:mismatches.length,lastRunAt:generatedAt});return{dryRun:!apply,inventoryComplete:complete,metadataCount,objectCount:objects.size,missingObjects:missing.slice(0,200),orphanObjects:orphans.slice(0,200),sizeMismatches:mismatches.slice(0,200),deletedOrphans:deleted,generatedAt};}
  public async requestReconciliation(actor:AuthorizedAdminProfile,correlationId:string):Promise<StorageReconciliationReport>{const report=await this.reconcile(false);await this.audit.write({eventType:'STORAGE_RECONCILIATION_REQUESTED',actorUid:actor.uid,actorEmail:actor.email,actorRole:actor.role,targetType:'storage',summary:'Reconciliação R2 × Firestore executada em modo somente relatório.',requestCorrelationId:correlationId,metadata:{missing:report.missingObjects.length,orphans:report.orphanObjects.length,sizeMismatches:report.sizeMismatches.length}});return report;}
}
