export type ApiErrorCode =
  | 'VALIDATION_ERROR'
  | 'UNAUTHENTICATED'
  | 'INVALID_TOKEN'
  | 'APP_CHECK_REQUIRED'
  | 'APP_CHECK_INVALID'
  | 'FORBIDDEN'
  | 'ADMIN_NOT_AUTHORIZED'
  | 'ADMIN_INACTIVE'
  | 'LEGACY_ROLE_REQUIRES_RESOLUTION'
  | 'DOMAIN_NOT_ALLOWED'
  | 'PROVIDER_NOT_ALLOWED'
  | 'EMAIL_NOT_VERIFIED'
  | 'UID_MISMATCH'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'PHOTO_TOO_LARGE'
  | 'PHOTO_COUNT_EXCEEDED'
  | 'PHOTO_TYPE_NOT_ALLOWED'
  | 'PHOTO_CORRUPTED'
  | 'PHOTO_DIMENSIONS_EXCEEDED'
  | 'PHOTO_PROCESSING_FAILED'
  | 'PHOTO_STORAGE_FAILED'
  | 'PHOTO_NOT_FOUND'
  | 'PHOTO_NOT_PUBLIC'
  | 'PHOTO_VERSION_CONFLICT'
  | 'REFERENCE_DATA_NOT_INITIALIZED'
  | 'FIREBASE_UNAVAILABLE'
  | 'CONFIGURATION_ERROR'
  | 'INTERNAL_ERROR'
  | 'NETWORK_ERROR'
  | 'UNKNOWN_ERROR';

export interface ApiErrorPayload {
  error: {
    code: ApiErrorCode;
    message: string;
    correlationId?: string;
    details?: Record<string, string[]>;
  };
}
