import { effectiveResolutionMinutes } from '../domain/sla';
import type { StoredOccurrence } from '../models/occurrenceDomain';

export const EXPORT_LIMIT = 2000;
export const EXPORT_HEADERS = [
  'Protocolo','Data de abertura','Data de encerramento','Categoria','Bloco/Área','Ambiente','Situação','Prioridade','Equipe','Responsável',
  'Risco imediato','Prazo primeira resposta','Primeira resposta','Resultado primeira resposta','SLA conclusão alvo (h úteis)','Prazo conclusão',
  'Resultado conclusão','Tempo total (h corridas)','Tempo efetivo (h úteis)','Pausa atual','SLA legado','Classificação',
];
function formulaSafe(value:string):string{return /^[=+\-@]/u.test(value)?`'${value}`:value;}
function values(o:StoredOccurrence):string[]{
  const now=o.closedAt??new Date();
  const totalHours=Math.max(0,(now.getTime()-o.createdAt.getTime())/3_600_000);
  const effective=o.sla?.calendarSnapshot ? effectiveResolutionMinutes(o.createdAt,now,o.sla,o.sla.calendarSnapshot)/60 : undefined;
  return [o.protocol,o.createdAt.toISOString(),o.closedAt?.toISOString()??'',o.categoryNameSnapshot,o.location.buildingName,o.location.room,o.status,o.priority,o.assignedTeamNameSnapshot??'',o.assignedToDisplayNameSnapshot??'',o.immediateRisk?'Sim':'Não',o.sla?.firstResponseDueAt.toISOString()??'',o.firstPublicResponseAt?.toISOString()??'',o.sla?.firstResponseOutcome??'',o.sla?String(o.sla.resolutionTargetBusinessMinutes/60):'',o.sla?.resolutionDueAt.toISOString()??'',o.sla?.resolutionOutcome??'',totalHours.toFixed(2),effective===undefined?'':effective.toFixed(2),o.sla?.resolutionPaused?'Sim':'Não',o.sla?.legacyAssessment??'',o.dataClassification].map(formulaSafe);
}
function csvEscape(v:string):string{return /[;"\n\r]/u.test(v)?`"${v.replace(/"/gu,'""')}"`:v;}
export function createCsv(items:StoredOccurrence[]):Buffer{const lines=[EXPORT_HEADERS,...items.map(values)].map(row=>row.map(csvEscape).join(';'));return Buffer.from(`\uFEFF${lines.join('\r\n')}`,'utf8');}
function xml(v:string):string{return v.replace(/&/gu,'&amp;').replace(/</gu,'&lt;').replace(/>/gu,'&gt;').replace(/"/gu,'&quot;');}
function colName(i:number):string{let n=i+1,s='';while(n){n-=1;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
function crc32(buf:Buffer):number{let crc=0xffffffff;for(const byte of buf){crc^=byte;for(let k=0;k<8;k+=1)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
function zip(files:Array<{name:string;data:Buffer}>):Buffer{const locals:Buffer[]=[];const centrals:Buffer[]=[];let offset=0;for(const f of files){const name=Buffer.from(f.name,'utf8');const crc=crc32(f.data);const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(0,6);local.writeUInt16LE(0,8);local.writeUInt16LE(0,10);local.writeUInt16LE(0,12);local.writeUInt32LE(crc,14);local.writeUInt32LE(f.data.length,18);local.writeUInt32LE(f.data.length,22);local.writeUInt16LE(name.length,26);local.writeUInt16LE(0,28);locals.push(local,name,f.data);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(0,8);central.writeUInt16LE(0,10);central.writeUInt16LE(0,12);central.writeUInt16LE(0,14);central.writeUInt32LE(crc,16);central.writeUInt32LE(f.data.length,20);central.writeUInt32LE(f.data.length,24);central.writeUInt16LE(name.length,28);central.writeUInt16LE(0,30);central.writeUInt16LE(0,32);central.writeUInt16LE(0,34);central.writeUInt16LE(0,36);central.writeUInt32LE(0,38);central.writeUInt32LE(offset,42);centrals.push(central,name);offset+=local.length+name.length+f.data.length;}const centralSize=centrals.reduce((n,b)=>n+b.length,0);const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(0,4);end.writeUInt16LE(0,6);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(centralSize,12);end.writeUInt32LE(offset,16);end.writeUInt16LE(0,20);return Buffer.concat([...locals,...centrals,end]);}
export function createXlsx(items:StoredOccurrence[]):Buffer{const rows=[EXPORT_HEADERS,...items.map(values)];const sheet=rows.map((row,r)=>`<row r="${r+1}">${row.map((v,c)=>`<c r="${colName(c)}${r+1}" t="inlineStr"${r===0?' s="1"':''}><is><t>${xml(v)}</t></is></c>`).join('')}</row>`).join('');const files=[
{name:'[Content_Types].xml',data:Buffer.from('<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>')},
{name:'_rels/.rels',data:Buffer.from('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>')},
{name:'xl/workbook.xml',data:Buffer.from('<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Ocorrências" sheetId="1" r:id="rId1"/></sheets></workbook>')},
{name:'xl/_rels/workbook.xml.rels',data:Buffer.from('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>')},
{name:'xl/styles.xml',data:Buffer.from('<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>')},
{name:'xl/worksheets/sheet1.xml',data:Buffer.from(`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${sheet}</sheetData></worksheet>`)}];return zip(files);}
function pdfEscape(s:string):string{return s.replace(/\\/gu,'\\\\').replace(/\(/gu,'\\(').replace(/\)/gu,'\\)');}
function wrap(s:string,n=96):string[]{const words=s.split(/\s+/u);const lines:string[]=[];let line='';for(const w of words){if((line+' '+w).trim().length>n){if(line)lines.push(line);line=w;}else line=(line+' '+w).trim();}if(line)lines.push(line);return lines;}
export function createPdf(items:StoredOccurrence[],title='Relatório de ocorrências'):Buffer{const lines=[title,'Sistema Institucional de Manutenção da Infraestrutura Física','Instituto Federal do Espírito Santo - Campus Barra de São Francisco',`Gerado em ${new Date().toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}`,'',...items.flatMap(o=>wrap(`${o.protocol} | ${o.createdAt.toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo'})} | ${o.categoryNameSnapshot} | ${o.location.buildingName} - ${o.location.room} | ${o.status} | ${o.priority} | ${o.assignedTeamNameSnapshot??'Sem equipe'}`))];const pages:Array<string[]>=[];for(let i=0;i<lines.length;i+=48)pages.push(lines.slice(i,i+48));const objects:string[]=[];objects.push('<< /Type /Catalog /Pages 2 0 R >>');const pageIds=pages.map((_,i)=>4+i*2);objects.push(`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pages.length} >>`);objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>');pages.forEach((page,i)=>{const pageId=4+i*2,contentId=5+i*2;objects[pageId-1]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`;const content=`BT /F1 9 Tf 40 800 Td 12 TL ${page.map((line,index)=>`${index===0?'':'T* '}(${pdfEscape(line)}) Tj`).join(' ')} ET`;const byteLength=Buffer.byteLength(content,'latin1');objects[contentId-1]=`<< /Length ${byteLength} >>\nstream\n${content}\nendstream`;});let pdf='%PDF-1.4\n';const offsets=[0];for(let i=0;i<objects.length;i+=1){offsets[i+1]=Buffer.byteLength(pdf,'latin1');pdf+=`${i+1} 0 obj\n${objects[i]??'<<>>'}\nendobj\n`;}const xref=Buffer.byteLength(pdf,'latin1');pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objects.length;i+=1)pdf+=`${String(offsets[i]??0).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf,'latin1');}
