import type { AuthorizedAdminProfile } from '../../src/models/admin';
import type { BuildingLocation, CampusLocation, CategoryItem, RoomLocation, SystemConfig } from '../../src/models/config';
import type { OperationalTeam, ServiceCalendar, ServiceCalendarException, SlaConfiguration, TeamCreateInput, TeamUpdateInput } from '../../src/models/operations';
import type { LocationDetail, LocationSelectionInput, OccurrenceFilterOptions } from '../../src/models/occurrence';
import { PRIORITY_RANK } from '../../src/models/occurrence';
import { formatProtocol } from '../../src/utils/protocol';
import { normalizeSearchKeyword } from '../../src/utils/textNormalization';
import type { NewOccurrenceEvent, NewOccurrenceRecord, OccurrenceEventRecord, StoredOccurrence } from '../../server/models/occurrenceDomain';
import type { StoredPhotoMetadata } from '../../server/models/photoDomain';
import type { NotificationOutboxItem } from '../../server/models/notificationDomain';
import { createOccurrenceNotificationItems } from '../../server/domain/notificationOutbox';
import type { CategoryMutation, CategoryRepository } from '../../server/repositories/categoryRepository';
import type { LocationRepository } from '../../server/repositories/locationRepository';
import type { OccurrenceEventRepository } from '../../server/repositories/occurrenceEventRepository';
import {
  DuplicateCycleError, DuplicateTargetNotFoundError, OccurrenceVersionConflictError,
  type OccurrenceCountFilter, type OccurrenceCreationPersistenceOptions, type OccurrenceOperationalPropagation, type OccurrencePhotoMutations, type OccurrenceRepository,
} from '../../server/repositories/occurrenceRepository';
import type { OperationalTeamRepository } from '../../server/repositories/operationalTeamRepository';
import type { SlaConfigRepository } from '../../server/repositories/slaConfigRepository';
import type { SystemConfigRepository } from '../../server/repositories/systemConfigRepository';
import { DEFAULT_SERVICE_CALENDAR, DEFAULT_SLA_CONFIG } from '../../server/repositories/referenceSeedData';

function clone<T>(value:T):T{return structuredClone(value);}
export class FakeOccurrenceEventRepository implements OccurrenceEventRepository {
  private readonly events=new Map<string,OccurrenceEventRecord[]>(); private sequence=0;
  public append(occurrenceId:string,values:NewOccurrenceEvent[]):void{const current=this.events.get(occurrenceId)??[];this.events.set(occurrenceId,[...current,...values.map(event=>({...clone(event),id:`event-${++this.sequence}`}))]);}
  public listByOccurrenceId(id:string):Promise<OccurrenceEventRecord[]>{return Promise.resolve(clone(this.events.get(id)??[]));}
  public deleteByOccurrenceId(id:string):void{this.events.delete(id);}
}
function day(d:Date):string{return d.toISOString().slice(0,10);}
function matches(item:StoredOccurrence,f:OccurrenceFilterOptions):boolean{
  if(f.protocol&&item.protocol!==f.protocol.trim().toUpperCase())return false;
  if(f.keyword){const token=normalizeSearchKeyword(f.keyword);if(token&&!item.searchTokens.includes(token))return false;}
  if(f.category&&item.categoryId!==f.category)return false;
  if(f.areaId&&item.location.buildingId!==f.areaId)return false;
  if(f.environmentId&&item.location.roomId!==f.environmentId)return false;
  if(f.status&&f.status!=='TODAS'&&item.status!==f.status)return false;
  if(f.priority&&f.priority!=='TODAS'&&item.priority!==f.priority)return false;
  if(f.assignedTeamId&&item.assignedTeamId!==f.assignedTeamId)return false;
  if(f.assignedToAdminUserId&&item.assignedToAdminUserId!==f.assignedToAdminUserId)return false;
  if(f.immediateRisk&&item.immediateRisk!==(f.immediateRisk==='true'))return false;
  if(f.withoutTeam&&item.assignedTeamId!==undefined)return false;
  if(f.withoutResponsible&&item.assignedToAdminUserId!==undefined)return false;
  if(f.withoutRouting&&item.assignedTeamId!==undefined&&item.assignedToAdminUserId!==undefined)return false;
  if(f.criticalPriority&&!['Urgente','Emergencial'].includes(item.priority))return false;
  if(f.awaitingAction&&!['Aguardando material','Aguardando contratação ou serviço externo'].includes(item.status))return false;
  if(f.withPhoto&& !item.hasPhoto)return false; if(f.withoutPhoto&&item.hasPhoto)return false;
  if(f.reopened&&item.reopenedCount<1)return false;const reopenedDay=item.lastReopenedAt?day(item.lastReopenedAt):undefined;if(f.reopenedStartDate&&(!reopenedDay||reopenedDay<f.reopenedStartDate))return false;if(f.reopenedEndDate&&(!reopenedDay||reopenedDay>f.reopenedEndDate))return false; if(f.dataClassification&&item.dataClassification!==f.dataClassification)return false;
  if(f.startDate&&day(item.createdAt)<f.startDate)return false;if(f.endDate&&day(item.createdAt)>f.endDate)return false;
  if(f.closedStartDate&&(!item.closedAt||day(item.closedAt)<f.closedStartDate))return false;if(f.closedEndDate&&(!item.closedAt||day(item.closedAt)>f.closedEndDate))return false;
  const now=new Date(); if(f.slaStatus==='PAUSED'&&item.sla?.resolutionPaused!==true)return false;if(f.slaStatus==='COMPLETED'&&!item.closedAt)return false;
  if(f.slaStatus==='BREACHED'&&(!item.sla||item.closedAt||item.sla.resolutionPaused||item.sla.resolutionDueAt>=now))return false;
  if(f.slaStatus==='NEAR_DUE'&&(!item.sla||item.closedAt||item.sla.resolutionPaused||item.sla.resolutionNearDueAt>now||item.sla.resolutionDueAt<now))return false;
  if(f.slaStatus==='ON_TIME'&&(!item.sla||item.closedAt||item.sla.resolutionPaused||item.sla.resolutionNearDueAt<=now))return false;
  return true;
}
function countMatch(item:StoredOccurrence,f:OccurrenceCountFilter):boolean{
 if(f.assignedToAdminUserId&&item.assignedToAdminUserId!==f.assignedToAdminUserId)return false;if(f.assignedTeamId&&item.assignedTeamId!==f.assignedTeamId)return false;
 if(f.status&&item.status!==f.status)return false;if(f.statuses&&!f.statuses.includes(item.status))return false;if(f.priorities&&!f.priorities.includes(item.priority))return false;
 if(f.createdAtFrom&&item.createdAt<f.createdAtFrom)return false;if(f.createdAtTo&&item.createdAt>f.createdAtTo)return false;if(f.resolvedAtFrom&&(!item.resolvedAt||item.resolvedAt<f.resolvedAtFrom))return false;if(f.resolvedAtTo&&(!item.resolvedAt||item.resolvedAt>f.resolvedAtTo))return false;
 if(f.closedAtFrom&&(!item.closedAt||item.closedAt<f.closedAtFrom))return false;if(f.closedAtTo&&(!item.closedAt||item.closedAt>f.closedAtTo))return false;if(f.isClosed!==undefined&&(item.closedAt!==undefined)!==f.isClosed)return false;
 if(f.hasTeam!==undefined&&(item.assignedTeamId!==undefined)!==f.hasTeam)return false;if(f.hasResponsible!==undefined&&(item.assignedToAdminUserId!==undefined)!==f.hasResponsible)return false;if(f.dataClassification&&item.dataClassification!==f.dataClassification)return false;
 if(f.slaBreachedAt&&(!item.sla||item.closedAt||item.sla.resolutionPaused||item.sla.resolutionDueAt>=f.slaBreachedAt))return false;return true;
}
function syncOperational(target:StoredOccurrence,source:StoredOccurrence):StoredOccurrence{const out:StoredOccurrence={...target,status:source.status,priority:source.priority,priorityRank:source.priorityRank,updatedAt:source.updatedAt,version:target.version+1,dataClassification:source.dataClassification,reopenedCount:source.reopenedCount,...(source.sla?{sla:clone(source.sla)}:{})};if(!source.sla)delete out.sla;if(source.assignedTeamId){out.assignedTeamId=source.assignedTeamId;out.assignedTeamNameSnapshot=source.assignedTeamNameSnapshot;}else{delete out.assignedTeamId;delete out.assignedTeamNameSnapshot;}if(source.assignedToAdminUserId){out.assignedToAdminUserId=source.assignedToAdminUserId;out.assignedToDisplayNameSnapshot=source.assignedToDisplayNameSnapshot;}else{delete out.assignedToAdminUserId;delete out.assignedToDisplayNameSnapshot;}if(source.closedAt)out.closedAt=source.closedAt;else delete out.closedAt;if(source.resolvedAt)out.resolvedAt=source.resolvedAt;else delete out.resolvedAt;if(source.firstPublicResponseAt)out.firstPublicResponseAt=source.firstPublicResponseAt;else delete out.firstPublicResponseAt;if(source.lastReopenedAt)out.lastReopenedAt=source.lastReopenedAt;else delete out.lastReopenedAt;return out;}
function order(items:StoredOccurrence[],sort:OccurrenceFilterOptions['sort']):StoredOccurrence[]{return items.sort((a,b)=>{switch(sort){case'oldest':return a.createdAt.getTime()-b.createdAt.getTime();case'protocol':return a.protocol.localeCompare(b.protocol);case'sla':return (a.sla?.resolutionDueAt.getTime()??Infinity)-(b.sla?.resolutionDueAt.getTime()??Infinity);case'priority':case'operational':default:return a.priorityRank-b.priorityRank||((a.sla?.resolutionDueAt.getTime()??Infinity)-(b.sla?.resolutionDueAt.getTime()??Infinity))||a.createdAt.getTime()-b.createdAt.getTime();case'newest':return b.createdAt.getTime()-a.createdAt.getTime();}});}
export interface FakePhotoMutationSink{create(id:string,photos:StoredPhotoMetadata[]):void;update(id:string,photos:StoredPhotoMetadata[]):void;deleteOccurrence?(id:string):void;}
export class FakeOccurrenceRepository implements OccurrenceRepository{
  private readonly items=new Map<string,StoredOccurrence>();private readonly counters=new Map<number,number>();private sequence=0;
  public readonly outboxItems: NotificationOutboxItem[] = [];
  public constructor(private readonly events:FakeOccurrenceEventRepository,private readonly photoSink?:FakePhotoMutationSink){}
  public async createWithProtocol(input:NewOccurrenceRecord,prefix:string,events:NewOccurrenceEvent[],options:OccurrenceCreationPersistenceOptions={}):Promise<StoredOccurrence>{await Promise.resolve();const now=events[0]?.createdAt??new Date();const year=Number(new Intl.DateTimeFormat('en',{year:'numeric',timeZone:'America/Sao_Paulo'}).format(now));const seq=(this.counters.get(year)??0)+1;this.counters.set(year,seq);const item:StoredOccurrence={id:options.occurrenceId??`occ-${++this.sequence}`,schemaVersion:2,protocol:formatProtocol(prefix,year,seq),trackingKeyHash:input.trackingKeyHash,trackingKeySalt:input.trackingKeySalt,reportedCategoryId:input.categoryId,reportedCategoryNameSnapshot:input.categoryNameSnapshot,categoryId:input.categoryId,categoryNameSnapshot:input.categoryNameSnapshot,reportedLocation:clone(input.location),location:clone(input.location),description:input.description,immediateRisk:input.immediateRisk,status:'Recebida',priority:input.priority,priorityRank:PRIORITY_RANK[input.priority],createdAt:now,updatedAt:now,version:1,dataClassification:input.dataClassification,reopenedCount:0,hasPhoto:(options.photos?.length??0)>0,searchTokens:clone(input.searchTokens),...(input.assignedTeamId?{assignedTeamId:input.assignedTeamId,assignedTeamNameSnapshot:input.assignedTeamNameSnapshot}:{}),...(input.sla?{sla:clone(input.sla)}:{})};this.items.set(item.id,clone(item));this.events.append(item.id,events);this.photoSink?.create(item.id,options.photos??[]);const notifications = createOccurrenceNotificationItems(item, options.notificationRecipients ?? [], now, options.notificationProvider ?? 'ews');this.outboxItems.push(...notifications);return clone(item);}
 public getById(id:string):Promise<StoredOccurrence|undefined>{const x=this.items.get(id);return Promise.resolve(x?clone(x):undefined);} public findByProtocol(protocol:string):Promise<StoredOccurrence|undefined>{const x=[...this.items.values()].find(v=>v.protocol===protocol.trim().toUpperCase());return Promise.resolve(x?clone(x):undefined);}
 public async list(filters:OccurrenceFilterOptions,_user:AuthorizedAdminProfile):Promise<{items:StoredOccurrence[];limit:number;hasMore:boolean;nextCursor?:string}>{void _user;await Promise.resolve();const size=filters.pageSize??25;const start=filters.cursor?Number(Buffer.from(filters.cursor,'base64url').toString('utf8')):0;const eligible=order([...this.items.values()].filter(v=>matches(v,filters)),filters.sort);const items=eligible.slice(start,start+size).map(clone);const next=start+items.length;return{items,limit:size,hasMore:next<eligible.length,...(next<eligible.length?{nextCursor:Buffer.from(String(next),'utf8').toString('base64url')}:{})};}
  public listForAnalytics(filters:OccurrenceFilterOptions,max:number):Promise<{items:StoredOccurrence[];truncated:boolean;total:number}>{const all=order([...this.items.values()].filter(x=>matches(x,filters)),'oldest');return Promise.resolve({items:all.slice(0,max).map(clone),truncated:all.length>max,total:all.length});}
  public listForExport(filters:OccurrenceFilterOptions,max:number):Promise<{items:StoredOccurrence[];truncated:boolean}>{const all=order([...this.items.values()].filter(x=>matches(x,filters)),filters.sort);return Promise.resolve({items:all.slice(0,max).map(clone),truncated:all.length>max});}
 public countFiltered(filters:OccurrenceFilterOptions):Promise<number>{return Promise.resolve([...this.items.values()].filter(x=>matches(x,filters)).length);}
 public async listAttachmentGroup(occurrenceId:string):Promise<StoredOccurrence[]>{await Promise.resolve();const current=this.items.get(occurrenceId);if(!current)return[];const rootId=current.attachedToOccurrenceId??current.id;return [...this.items.values()].filter(item=>item.id===rootId||item.attachedToOccurrenceId===rootId).map(clone);}
  public async updateWithEvents(next:StoredOccurrence,expectedVersion:number,events:NewOccurrenceEvent[],photoMutations:OccurrencePhotoMutations={},notificationItems:NotificationOutboxItem[]=[],propagation?:OccurrenceOperationalPropagation):Promise<StoredOccurrence>{await Promise.resolve();const current=this.items.get(next.id);if(!current)throw new Error('OCCURRENCE_NOT_FOUND');if(current.version!==expectedVersion)throw new OccurrenceVersionConflictError();if(next.duplicateOfOccurrenceId){if(!this.items.has(next.duplicateOfOccurrenceId))throw new DuplicateTargetNotFoundError();if(await this.wouldCreateDuplicateCycle(next.id,next.duplicateOfOccurrenceId))throw new DuplicateCycleError();}this.items.set(next.id,clone(next));this.events.append(next.id,events);if(propagation?.enabled){const rootId=current.attachedToOccurrenceId??current.id;for(const [memberId,member] of this.items.entries()){if(memberId===next.id)continue;if(memberId!==rootId&&member.attachedToOccurrenceId!==rootId)continue;const synced=syncOperational(member,next);this.items.set(memberId,clone(synced));this.events.append(memberId,propagation.events);}}this.photoSink?.create(next.id,photoMutations.create??[]);this.photoSink?.update(next.id,photoMutations.update??[]);this.outboxItems.push(...notificationItems);return clone(next);}
  public async wouldCreateDuplicateCycle(sourceId:string,targetId:string):Promise<boolean>{await Promise.resolve();if(sourceId===targetId)return true;const visited=new Set<string>();let id:string|undefined=targetId;for(let i=0;i<100&&id;i++){if(id===sourceId||visited.has(id))return true;visited.add(id);id=this.items.get(id)?.duplicateOfOccurrenceId;}return id!==undefined;}
  public count(f:OccurrenceCountFilter):Promise<number>{return Promise.resolve([...this.items.values()].filter(x=>countMatch(x,f)).length);} public async deleteOccurrenceTree(id:string):Promise<void>{await Promise.resolve();this.items.delete(id);this.events.deleteByOccurrenceId(id);this.photoSink?.deleteOccurrence?.(id);} public setDirect(item:StoredOccurrence):void{this.items.set(item.id,clone(item));}
  public isLocationReferenced(buildingId:string,roomId?:string):Promise<boolean>{const matches=[...this.items.values()].some((item)=>{if(roomId)return item.location.buildingId===buildingId&&item.location.roomId===roomId;return item.location.buildingId===buildingId;});return Promise.resolve(matches);}
}
export class FakeCategoryRepository implements CategoryRepository{
 public constructor(private items:CategoryItem[]){} public listActive():Promise<CategoryItem[]>{return Promise.resolve(clone(this.items.filter(x=>x.active)));}public listAll():Promise<CategoryItem[]>{return Promise.resolve(clone(this.items));}public getById(id:string):Promise<CategoryItem|undefined>{const x=this.items.find(v=>v.id===id);return Promise.resolve(x?clone(x):undefined);}
 public create(item:Omit<CategoryItem,'id'|'version'>&{id:string},_by:string):Promise<CategoryItem>{void _by;const x:{id:string}&Omit<CategoryItem,'id'>={...item,version:1};this.items.push(x);return Promise.resolve(clone(x));}
 public update(id:string,input:CategoryMutation,_by:string):Promise<CategoryItem>{void _by;const i=this.items.findIndex(x=>x.id===id);if(i<0)return Promise.reject(new Error('CATEGORY_NOT_FOUND'));const before=this.items[i]!;if(before.version!==input.expectedVersion)return Promise.reject(new Error('CONFLICT'));const after={...before,...input,version:before.version+1};delete (after as Partial<CategoryMutation>).expectedVersion;this.items[i]=after;return Promise.resolve(clone(after));}
 public seed(items:CategoryItem[],_by:string):Promise<void>{void _by;for(const x of items)if(!this.items.some(y=>y.id===x.id))this.items.push(clone(x));return Promise.resolve();}
}
export class FakeLocationRepository implements LocationRepository{
 public constructor(private items:CampusLocation[]){} public list():Promise<CampusLocation[]>{return Promise.resolve(clone(this.items));}public getCampus(id:string):Promise<CampusLocation|undefined>{const x=this.items.find(v=>v.id===id);return Promise.resolve(x?clone(x):undefined);}
  public listActiveForPublic():Promise<CampusLocation[]>{const filtered=this.items.map(campus=>({...clone(campus),buildings:campus.buildings.filter(b=>b.active!==false).map(b=>({...clone(b),floors:b.floors.map(f=>({...clone(f),rooms:f.rooms.filter(r=>r.active!==false)}))}))}));return Promise.resolve(filtered);}
  public resolveSnapshot(input:LocationSelectionInput):Promise<LocationDetail|undefined>{const c=this.items.find(x=>x.id===input.campusId),b=c?.buildings.find(x=>x.id===input.buildingId&&x.active!==false),f=b?.floors.find(x=>x.id===input.floorId),r=f?.rooms.find(x=>x.id===input.roomId&&x.active!==false);if(!c||!b||!f||!r)return Promise.resolve(undefined);return Promise.resolve({campusId:c.id,campusName:c.campusName,buildingId:b.id,buildingName:b.name,floorId:f.id,floor:f.name,roomId:r.id,room:r.name,...(input.complement?{complement:input.complement}:{}),...(input.isOther===undefined?{}:{isOther:input.isOther}),...(input.otherDescription?{otherDescription:input.otherDescription}:{})});}
  public seed(items:CampusLocation[],_by:string):Promise<void>{void _by;for(const seed of items){const current=this.items.find(x=>x.id===seed.id);if(!current){this.items.push(clone(seed));continue;}for(const area of seed.buildings){const a=current.buildings.find(x=>x.id===area.id);if(!a){current.buildings.push(clone(area));continue;}for(const room of area.floors[0]?.rooms??[])if(!a.floors[0]?.rooms.some(x=>x.id===room.id))a.floors[0]?.rooms.push(clone(room));}}return Promise.resolve();}
  private mutate(campusId:string,expected:number,fn:(c:CampusLocation)=>void):Promise<CampusLocation>{const c=this.items.find(x=>x.id===campusId);if(!c)return Promise.reject(new Error('LOCATION_NOT_FOUND'));if((c.version??1)!==expected)return Promise.reject(new Error('CONFLICT'));fn(c);c.version=(c.version??1)+1;return Promise.resolve(clone(c));}
  public addArea(campusId:string,area:BuildingLocation,expectedVersion:number,_by:string):Promise<CampusLocation>{void _by;return this.mutate(campusId,expectedVersion,c=>c.buildings.push(clone(area)));}
  public updateArea(campusId:string,areaId:string,input:{name?:string;active?:boolean;sortOrder?:number;expectedVersion:number},_by:string):Promise<CampusLocation>{void _by;return this.mutate(campusId,input.expectedVersion,c=>{const a=c.buildings.find(x=>x.id===areaId);if(!a)throw new Error('AREA_NOT_FOUND');Object.assign(a,{...(input.name===undefined?{}:{name:input.name}),...(input.active===undefined?{}:{active:input.active}),...(input.sortOrder===undefined?{}:{sortOrder:input.sortOrder})});});}
  public deleteArea(campusId:string,areaId:string,expectedVersion:number,_by:string):Promise<CampusLocation>{void _by;return this.mutate(campusId,expectedVersion,c=>{const len=c.buildings.length;c.buildings=c.buildings.filter(b=>b.id!==areaId);if(c.buildings.length===len)throw new Error('AREA_NOT_FOUND');});}
  public addEnvironment(campusId:string,areaId:string,room:RoomLocation,expectedVersion:number,_by:string):Promise<CampusLocation>{void _by;return this.mutate(campusId,expectedVersion,c=>{const f=c.buildings.find(x=>x.id===areaId)?.floors[0];if(!f)throw new Error('AREA_NOT_FOUND');f.rooms.push(clone(room));});}
  public updateEnvironment(campusId:string,areaId:string,roomId:string,input:{name?:string;active?:boolean;sortOrder?:number;expectedVersion:number},_by:string):Promise<CampusLocation>{void _by;return this.mutate(campusId,input.expectedVersion,c=>{const r=c.buildings.find(x=>x.id===areaId)?.floors[0]?.rooms.find(x=>x.id===roomId);if(!r)throw new Error('ROOM_NOT_FOUND');Object.assign(r,{...(input.name===undefined?{}:{name:input.name}),...(input.active===undefined?{}:{active:input.active}),...(input.sortOrder===undefined?{}:{sortOrder:input.sortOrder})});});}
  public deleteEnvironment(campusId:string,areaId:string,roomId:string,expectedVersion:number,_by:string):Promise<CampusLocation>{void _by;return this.mutate(campusId,expectedVersion,c=>{const a=c.buildings.find(x=>x.id===areaId);if(!a||!a.floors[0])throw new Error('AREA_NOT_FOUND');const f=a.floors[0];const len=f.rooms.length;f.rooms=f.rooms.filter(r=>r.id!==roomId);if(f.rooms.length===len)throw new Error('ROOM_NOT_FOUND');});}
}
export class FakeSystemConfigRepository implements SystemConfigRepository{public constructor(private value:SystemConfig|undefined){}public get():Promise<SystemConfig|undefined>{return Promise.resolve(this.value?clone(this.value):undefined);}public update(c:SystemConfig,_by:string):Promise<SystemConfig>{void _by;this.value=clone(c);return Promise.resolve(clone(c));}public seed(c:SystemConfig,_by:string):Promise<void>{void _by;if(!this.value)this.value=clone(c);return Promise.resolve();}}
export class FakeOperationalTeamRepository implements OperationalTeamRepository{
 private items:OperationalTeam[];public constructor(seed:OperationalTeam[]=[]){this.items=clone(seed);}public list(includeInactive=true):Promise<OperationalTeam[]>{return Promise.resolve(clone(this.items.filter(x=>includeInactive||x.active)));}public getById(id:string):Promise<OperationalTeam|undefined>{const x=this.items.find(v=>v.id===id);return Promise.resolve(x?clone(x):undefined);}
 public getInitialIntakeTeam():Promise<OperationalTeam|undefined>{const x=this.items.find(v=>v.active&&v.isInitialIntakeTeam);return Promise.resolve(x?clone(x):undefined);}
 public create(id:string,input:TeamCreateInput,actorId:string):Promise<OperationalTeam>{const now=new Date().toISOString();if(input.isInitialIntakeTeam){for(const t of this.items)t.isInitialIntakeTeam=false;}const x:OperationalTeam={id,schemaVersion:2,name:input.name,...(input.description?{description:input.description}:{}),...(input.notificationEmail?{notificationEmail:input.notificationEmail}:{}),isInitialIntakeTeam:input.isInitialIntakeTeam??false,active:input.active??true,sortOrder:input.sortOrder,memberAdminUserIds:input.memberAdminUserIds??[],createdAt:now,createdBy:actorId,updatedAt:now,updatedBy:actorId};this.items.push(x);return Promise.resolve(clone(x));}
 public update(id:string,input:TeamUpdateInput,actorId:string):Promise<OperationalTeam>{const i=this.items.findIndex(x=>x.id===id);if(i<0)return Promise.reject(new Error('TEAM_NOT_FOUND'));if(input.isInitialIntakeTeam){for(const t of this.items){if(t.id!==id)t.isInitialIntakeTeam=false;}}const current=this.items[i]!;const email=input.notificationEmail===null?undefined:(input.notificationEmail??current.notificationEmail);const x:OperationalTeam={...current,...input,notificationEmail:email,updatedAt:new Date().toISOString(),updatedBy:actorId};if(!x.notificationEmail)delete x.notificationEmail;this.items[i]=x;return Promise.resolve(clone(x));}
 public seed(teams:OperationalTeam[],_actorId:string):Promise<void>{void _actorId;for(const t of teams){if(!this.items.some(e=>e.id===t.id))this.items.push(clone(t));}return Promise.resolve();}
}
export class FakeSlaConfigRepository implements SlaConfigRepository{
 private sla:SlaConfiguration=clone(DEFAULT_SLA_CONFIG);private calendar:ServiceCalendar=clone(DEFAULT_SERVICE_CALENDAR);private exceptions:ServiceCalendarException[]=[];
 public getSlaConfig():Promise<SlaConfiguration>{return Promise.resolve(clone(this.sla));}public updateSlaConfig(input:SlaConfiguration,expectedVersion:number,actorId:string):Promise<SlaConfiguration>{if(this.sla.version!==expectedVersion)return Promise.reject(new Error('CONFLICT'));this.sla={...clone(input),version:expectedVersion+1,updatedAt:new Date().toISOString(),updatedBy:actorId};return Promise.resolve(clone(this.sla));}
 public getCalendar():Promise<ServiceCalendar>{return Promise.resolve(clone(this.calendar));}public updateCalendar(input:ServiceCalendar,expectedVersion:number,actorId:string):Promise<ServiceCalendar>{if(this.calendar.version!==expectedVersion)return Promise.reject(new Error('CONFLICT'));this.calendar={...clone(input),version:expectedVersion+1,updatedAt:new Date().toISOString(),updatedBy:actorId};return Promise.resolve(clone(this.calendar));}
 public listExceptions():Promise<ServiceCalendarException[]>{return Promise.resolve(clone(this.exceptions));}public getException(id:string):Promise<ServiceCalendarException|undefined>{const x=this.exceptions.find(v=>v.id===id);return Promise.resolve(x?clone(x):undefined);}public upsertException(input:Omit<ServiceCalendarException,'createdAt'|'createdBy'|'updatedAt'|'updatedBy'>,actorId:string):Promise<ServiceCalendarException>{const now=new Date().toISOString(),existing=this.exceptions.find(x=>x.id===input.id);const x:ServiceCalendarException={...clone(input),createdAt:existing?.createdAt??now,createdBy:existing?.createdBy??actorId,updatedAt:now,updatedBy:actorId};this.exceptions=this.exceptions.filter(y=>y.id!==x.id);this.exceptions.push(x);return Promise.resolve(clone(x));}public deleteException(id:string):Promise<void>{this.exceptions=this.exceptions.filter(x=>x.id!==id);return Promise.resolve();}public seedDefaults(_actorId:string):Promise<void>{void _actorId;return Promise.resolve();}
}

